// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class CharacterSelectionHandle : RemoteTableHandle<EventContext, CharacterSelection>
        {
            public override string RemoteTableName => "character_selection";

            public sealed class AccountIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(CharacterSelection row) => row.AccountId;

                public AccountIdIndex(CharacterSelectionHandle table) : base(table) { }
            }

            public readonly AccountIdIndex AccountId;

            public sealed class CharacterIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(CharacterSelection row) => row.CharacterId;

                public CharacterIdIndex(CharacterSelectionHandle table) : base(table) { }
            }

            public readonly CharacterIdIndex CharacterId;

            public sealed class ConnectionIdUniqueIndex : UniqueIndexBase<SpacetimeDB.ConnectionId>
            {
                protected override SpacetimeDB.ConnectionId GetKey(CharacterSelection row) => row.ConnectionId;

                public ConnectionIdUniqueIndex(CharacterSelectionHandle table) : base(table) { }
            }

            public readonly ConnectionIdUniqueIndex ConnectionId;

            public sealed class IdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(CharacterSelection row) => row.Identity;

                public IdentityIndex(CharacterSelectionHandle table) : base(table) { }
            }

            public readonly IdentityIndex Identity;

            internal CharacterSelectionHandle(DbConnection conn) : base(conn)
            {
                AccountId = new(this);
                CharacterId = new(this);
                ConnectionId = new(this);
                Identity = new(this);
            }

            protected override object GetPrimaryKey(CharacterSelection row) => row.ConnectionId;
        }

        public readonly CharacterSelectionHandle CharacterSelection;
    }

    public sealed class CharacterSelectionCols
    {
        public global::SpacetimeDB.Col<CharacterSelection, SpacetimeDB.ConnectionId> ConnectionId { get; }
        public global::SpacetimeDB.Col<CharacterSelection, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<CharacterSelection, ulong> AccountId { get; }
        public global::SpacetimeDB.Col<CharacterSelection, ulong> CharacterId { get; }
        public global::SpacetimeDB.Col<CharacterSelection, string> CharacterName { get; }
        public global::SpacetimeDB.Col<CharacterSelection, uint> JobId { get; }
        public global::SpacetimeDB.Col<CharacterSelection, uint> Level { get; }
        public global::SpacetimeDB.Col<CharacterSelection, SpacetimeDB.Timestamp> EnteredAt { get; }
        public global::SpacetimeDB.Col<CharacterSelection, uint> SpecId { get; }

        public CharacterSelectionCols(string tableName)
        {
            ConnectionId = new global::SpacetimeDB.Col<CharacterSelection, SpacetimeDB.ConnectionId>(tableName, "connection_id");
            Identity = new global::SpacetimeDB.Col<CharacterSelection, SpacetimeDB.Identity>(tableName, "identity");
            AccountId = new global::SpacetimeDB.Col<CharacterSelection, ulong>(tableName, "account_id");
            CharacterId = new global::SpacetimeDB.Col<CharacterSelection, ulong>(tableName, "character_id");
            CharacterName = new global::SpacetimeDB.Col<CharacterSelection, string>(tableName, "character_name");
            JobId = new global::SpacetimeDB.Col<CharacterSelection, uint>(tableName, "job_id");
            Level = new global::SpacetimeDB.Col<CharacterSelection, uint>(tableName, "level");
            EnteredAt = new global::SpacetimeDB.Col<CharacterSelection, SpacetimeDB.Timestamp>(tableName, "entered_at");
            SpecId = new global::SpacetimeDB.Col<CharacterSelection, uint>(tableName, "spec_id");
        }
    }

    public sealed class CharacterSelectionIxCols
    {
        public global::SpacetimeDB.IxCol<CharacterSelection, SpacetimeDB.ConnectionId> ConnectionId { get; }
        public global::SpacetimeDB.IxCol<CharacterSelection, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.IxCol<CharacterSelection, ulong> AccountId { get; }
        public global::SpacetimeDB.IxCol<CharacterSelection, ulong> CharacterId { get; }

        public CharacterSelectionIxCols(string tableName)
        {
            ConnectionId = new global::SpacetimeDB.IxCol<CharacterSelection, SpacetimeDB.ConnectionId>(tableName, "connection_id");
            Identity = new global::SpacetimeDB.IxCol<CharacterSelection, SpacetimeDB.Identity>(tableName, "identity");
            AccountId = new global::SpacetimeDB.IxCol<CharacterSelection, ulong>(tableName, "account_id");
            CharacterId = new global::SpacetimeDB.IxCol<CharacterSelection, ulong>(tableName, "character_id");
        }
    }
}
