// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class CharacterTransformHandle : RemoteTableHandle<EventContext, CharacterTransform>
        {
            public override string RemoteTableName => "character_transform";

            public sealed class CharacterIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(CharacterTransform row) => row.CharacterId;

                public CharacterIdIndex(CharacterTransformHandle table) : base(table) { }
            }

            public readonly CharacterIdIndex CharacterId;

            public sealed class ConnectionIdUniqueIndex : UniqueIndexBase<SpacetimeDB.ConnectionId>
            {
                protected override SpacetimeDB.ConnectionId GetKey(CharacterTransform row) => row.ConnectionId;

                public ConnectionIdUniqueIndex(CharacterTransformHandle table) : base(table) { }
            }

            public readonly ConnectionIdUniqueIndex ConnectionId;

            public sealed class TownIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(CharacterTransform row) => row.TownId;

                public TownIdIndex(CharacterTransformHandle table) : base(table) { }
            }

            public readonly TownIdIndex TownId;

            internal CharacterTransformHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
                ConnectionId = new(this);
                TownId = new(this);
            }

            protected override object GetPrimaryKey(CharacterTransform row) => row.ConnectionId;
        }

        public readonly CharacterTransformHandle CharacterTransform;
    }

    public sealed class CharacterTransformCols
    {
        public global::SpacetimeDB.Col<CharacterTransform, SpacetimeDB.ConnectionId> ConnectionId { get; }
        public global::SpacetimeDB.Col<CharacterTransform, uint> TownId { get; }
        public global::SpacetimeDB.Col<CharacterTransform, ulong> CharacterId { get; }
        public global::SpacetimeDB.Col<CharacterTransform, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<CharacterTransform, float> X { get; }
        public global::SpacetimeDB.Col<CharacterTransform, float> Y { get; }
        public global::SpacetimeDB.Col<CharacterTransform, int> Facing { get; }
        public global::SpacetimeDB.Col<CharacterTransform, bool> Moving { get; }
        public global::SpacetimeDB.Col<CharacterTransform, SpacetimeDB.Timestamp> UpdatedAt { get; }

        public CharacterTransformCols(string tableName)
        {
            ConnectionId = new global::SpacetimeDB.Col<CharacterTransform, SpacetimeDB.ConnectionId>(tableName, "connection_id");
            TownId = new global::SpacetimeDB.Col<CharacterTransform, uint>(tableName, "town_id");
            CharacterId = new global::SpacetimeDB.Col<CharacterTransform, ulong>(tableName, "character_id");
            Identity = new global::SpacetimeDB.Col<CharacterTransform, SpacetimeDB.Identity>(tableName, "identity");
            X = new global::SpacetimeDB.Col<CharacterTransform, float>(tableName, "x");
            Y = new global::SpacetimeDB.Col<CharacterTransform, float>(tableName, "y");
            Facing = new global::SpacetimeDB.Col<CharacterTransform, int>(tableName, "facing");
            Moving = new global::SpacetimeDB.Col<CharacterTransform, bool>(tableName, "moving");
            UpdatedAt = new global::SpacetimeDB.Col<CharacterTransform, SpacetimeDB.Timestamp>(tableName, "updated_at");
        }
    }

    public sealed class CharacterTransformIxCols
    {
        public global::SpacetimeDB.IxCol<CharacterTransform, SpacetimeDB.ConnectionId> ConnectionId { get; }
        public global::SpacetimeDB.IxCol<CharacterTransform, uint> TownId { get; }
        public global::SpacetimeDB.IxCol<CharacterTransform, ulong> CharacterId { get; }

        public CharacterTransformIxCols(string tableName)
        {
            ConnectionId = new global::SpacetimeDB.IxCol<CharacterTransform, SpacetimeDB.ConnectionId>(tableName, "connection_id");
            TownId = new global::SpacetimeDB.IxCol<CharacterTransform, uint>(tableName, "town_id");
            CharacterId = new global::SpacetimeDB.IxCol<CharacterTransform, ulong>(tableName, "character_id");
        }
    }
}
