// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class ChatMessageHandle : RemoteTableHandle<EventContext, ChatMessage>
        {
            public override string RemoteTableName => "chat_message";

            public sealed class MessageIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ChatMessage row) => row.MessageId;

                public MessageIdUniqueIndex(ChatMessageHandle table) : base(table) { }
            }

            public readonly MessageIdUniqueIndex MessageId;

            public sealed class SenderCharacterIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ChatMessage row) => row.SenderCharacterId;

                public SenderCharacterIdIndex(ChatMessageHandle table) : base(table) { }
            }

            public readonly SenderCharacterIdIndex SenderCharacterId;

            public sealed class TownIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(ChatMessage row) => row.TownId;

                public TownIdIndex(ChatMessageHandle table) : base(table) { }
            }

            public readonly TownIdIndex TownId;

            internal ChatMessageHandle(DbConnection conn) : base(conn)
            {
                MessageId = new(this);
                SenderCharacterId = new(this);
                TownId = new(this);
            }

            protected override object GetPrimaryKey(ChatMessage row) => row.MessageId;
        }

        public readonly ChatMessageHandle ChatMessage;
    }

    public sealed class ChatMessageCols
    {
        public global::SpacetimeDB.Col<ChatMessage, ulong> MessageId { get; }
        public global::SpacetimeDB.Col<ChatMessage, uint> Channel { get; }
        public global::SpacetimeDB.Col<ChatMessage, uint> TownId { get; }
        public global::SpacetimeDB.Col<ChatMessage, ulong> SenderCharacterId { get; }
        public global::SpacetimeDB.Col<ChatMessage, string> SenderName { get; }
        public global::SpacetimeDB.Col<ChatMessage, string> Content { get; }
        public global::SpacetimeDB.Col<ChatMessage, SpacetimeDB.Timestamp> SentAt { get; }
        public global::SpacetimeDB.Col<ChatMessage, uint> SenderJobId { get; }
        public global::SpacetimeDB.Col<ChatMessage, uint> SenderFormId { get; }

        public ChatMessageCols(string tableName)
        {
            MessageId = new global::SpacetimeDB.Col<ChatMessage, ulong>(tableName, "message_id");
            Channel = new global::SpacetimeDB.Col<ChatMessage, uint>(tableName, "channel");
            TownId = new global::SpacetimeDB.Col<ChatMessage, uint>(tableName, "town_id");
            SenderCharacterId = new global::SpacetimeDB.Col<ChatMessage, ulong>(tableName, "sender_character_id");
            SenderName = new global::SpacetimeDB.Col<ChatMessage, string>(tableName, "sender_name");
            Content = new global::SpacetimeDB.Col<ChatMessage, string>(tableName, "content");
            SentAt = new global::SpacetimeDB.Col<ChatMessage, SpacetimeDB.Timestamp>(tableName, "sent_at");
            SenderJobId = new global::SpacetimeDB.Col<ChatMessage, uint>(tableName, "sender_job_id");
            SenderFormId = new global::SpacetimeDB.Col<ChatMessage, uint>(tableName, "sender_form_id");
        }
    }

    public sealed class ChatMessageIxCols
    {
        public global::SpacetimeDB.IxCol<ChatMessage, ulong> MessageId { get; }
        public global::SpacetimeDB.IxCol<ChatMessage, uint> TownId { get; }
        public global::SpacetimeDB.IxCol<ChatMessage, ulong> SenderCharacterId { get; }

        public ChatMessageIxCols(string tableName)
        {
            MessageId = new global::SpacetimeDB.IxCol<ChatMessage, ulong>(tableName, "message_id");
            TownId = new global::SpacetimeDB.IxCol<ChatMessage, uint>(tableName, "town_id");
            SenderCharacterId = new global::SpacetimeDB.IxCol<ChatMessage, ulong>(tableName, "sender_character_id");
        }
    }
}
