// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class MyAccountProfileHandle : RemoteTableHandle<EventContext, MyAccountProfileRow>
        {
            public override string RemoteTableName => "my_account_profile";

            public sealed class AccountIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MyAccountProfileRow row) => row.AccountId;

                public AccountIdUniqueIndex(MyAccountProfileHandle table) : base(table) { }
            }

            public readonly AccountIdUniqueIndex AccountId;

            internal MyAccountProfileHandle(DbConnection conn) : base(conn)
            {
                AccountId = new(this);
            }

            protected override object GetPrimaryKey(MyAccountProfileRow row) => row.AccountId;
        }

        public readonly MyAccountProfileHandle MyAccountProfile;
    }

    public sealed class MyAccountProfileCols
    {
        public global::SpacetimeDB.Col<MyAccountProfileRow, ulong> AccountId { get; }
        public global::SpacetimeDB.Col<MyAccountProfileRow, string> Username { get; }
        public global::SpacetimeDB.Col<MyAccountProfileRow, uint> CharacterSlots { get; }

        public MyAccountProfileCols(string tableName)
        {
            AccountId = new global::SpacetimeDB.Col<MyAccountProfileRow, ulong>(tableName, "account_id");
            Username = new global::SpacetimeDB.Col<MyAccountProfileRow, string>(tableName, "username");
            CharacterSlots = new global::SpacetimeDB.Col<MyAccountProfileRow, uint>(tableName, "character_slots");
        }
    }

    public sealed class MyAccountProfileIxCols
    {
        public global::SpacetimeDB.IxCol<MyAccountProfileRow, ulong> AccountId { get; }

        public MyAccountProfileIxCols(string tableName)
        {
            AccountId = new global::SpacetimeDB.IxCol<MyAccountProfileRow, ulong>(tableName, "account_id");
        }
    }
}
