// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class MyCharacterHandle : RemoteTableHandle<EventContext, MyCharacterRow>
        {
            public override string RemoteTableName => "my_character";

            public sealed class CharacterIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MyCharacterRow row) => row.CharacterId;

                public CharacterIdUniqueIndex(MyCharacterHandle table) : base(table) { }
            }

            public readonly CharacterIdUniqueIndex CharacterId;

            internal MyCharacterHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
            }

            protected override object GetPrimaryKey(MyCharacterRow row) => row.CharacterId;
        }

        public readonly MyCharacterHandle MyCharacter;
    }

    public sealed class MyCharacterCols
    {
        public global::SpacetimeDB.Col<MyCharacterRow, ulong> CharacterId { get; }
        public global::SpacetimeDB.Col<MyCharacterRow, string> Name { get; }
        public global::SpacetimeDB.Col<MyCharacterRow, uint> JobId { get; }
        public global::SpacetimeDB.Col<MyCharacterRow, uint> Star { get; }
        public global::SpacetimeDB.Col<MyCharacterRow, uint> FormId { get; }
        public global::SpacetimeDB.Col<MyCharacterRow, uint> Level { get; }
        public global::SpacetimeDB.Col<MyCharacterRow, ulong> Exp { get; }
        public global::SpacetimeDB.Col<MyCharacterRow, uint> Stamina { get; }
        public global::SpacetimeDB.Col<MyCharacterRow, SpacetimeDB.Timestamp> CreatedAt { get; }
        public global::SpacetimeDB.Col<MyCharacterRow, SpacetimeDB.Timestamp> LastPlayedAt { get; }

        public MyCharacterCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.Col<MyCharacterRow, ulong>(tableName, "character_id");
            Name = new global::SpacetimeDB.Col<MyCharacterRow, string>(tableName, "name");
            JobId = new global::SpacetimeDB.Col<MyCharacterRow, uint>(tableName, "job_id");
            Star = new global::SpacetimeDB.Col<MyCharacterRow, uint>(tableName, "star");
            FormId = new global::SpacetimeDB.Col<MyCharacterRow, uint>(tableName, "form_id");
            Level = new global::SpacetimeDB.Col<MyCharacterRow, uint>(tableName, "level");
            Exp = new global::SpacetimeDB.Col<MyCharacterRow, ulong>(tableName, "exp");
            Stamina = new global::SpacetimeDB.Col<MyCharacterRow, uint>(tableName, "stamina");
            CreatedAt = new global::SpacetimeDB.Col<MyCharacterRow, SpacetimeDB.Timestamp>(tableName, "created_at");
            LastPlayedAt = new global::SpacetimeDB.Col<MyCharacterRow, SpacetimeDB.Timestamp>(tableName, "last_played_at");
        }
    }

    public sealed class MyCharacterIxCols
    {
        public global::SpacetimeDB.IxCol<MyCharacterRow, ulong> CharacterId { get; }

        public MyCharacterIxCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.IxCol<MyCharacterRow, ulong>(tableName, "character_id");
        }
    }
}
