// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class MyWalletHandle : RemoteTableHandle<EventContext, MyWalletRow>
        {
            public override string RemoteTableName => "my_wallet";

            public sealed class AccountIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MyWalletRow row) => row.AccountId;

                public AccountIdUniqueIndex(MyWalletHandle table) : base(table) { }
            }

            public readonly AccountIdUniqueIndex AccountId;

            internal MyWalletHandle(DbConnection conn) : base(conn)
            {
                AccountId = new(this);
            }

            protected override object GetPrimaryKey(MyWalletRow row) => row.AccountId;
        }

        public readonly MyWalletHandle MyWallet;
    }

    public sealed class MyWalletCols
    {
        public global::SpacetimeDB.Col<MyWalletRow, ulong> AccountId { get; }
        public global::SpacetimeDB.Col<MyWalletRow, ulong> Coin { get; }
        public global::SpacetimeDB.Col<MyWalletRow, ulong> Gem { get; }

        public MyWalletCols(string tableName)
        {
            AccountId = new global::SpacetimeDB.Col<MyWalletRow, ulong>(tableName, "account_id");
            Coin = new global::SpacetimeDB.Col<MyWalletRow, ulong>(tableName, "coin");
            Gem = new global::SpacetimeDB.Col<MyWalletRow, ulong>(tableName, "gem");
        }
    }

    public sealed class MyWalletIxCols
    {
        public global::SpacetimeDB.IxCol<MyWalletRow, ulong> AccountId { get; }

        public MyWalletIxCols(string tableName)
        {
            AccountId = new global::SpacetimeDB.IxCol<MyWalletRow, ulong>(tableName, "account_id");
        }
    }
}
