// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class SessionHandle : RemoteTableHandle<EventContext, Session>
        {
            public override string RemoteTableName => "session";

            public sealed class AccountIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Session row) => row.AccountId;

                public AccountIdIndex(SessionHandle table) : base(table) { }
            }

            public readonly AccountIdIndex AccountId;

            public sealed class ConnectionIdUniqueIndex : UniqueIndexBase<SpacetimeDB.ConnectionId>
            {
                protected override SpacetimeDB.ConnectionId GetKey(Session row) => row.ConnectionId;

                public ConnectionIdUniqueIndex(SessionHandle table) : base(table) { }
            }

            public readonly ConnectionIdUniqueIndex ConnectionId;

            public sealed class IdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Session row) => row.Identity;

                public IdentityIndex(SessionHandle table) : base(table) { }
            }

            public readonly IdentityIndex Identity;

            internal SessionHandle(DbConnection conn) : base(conn)
            {
                AccountId = new(this);
                ConnectionId = new(this);
                Identity = new(this);
            }

            protected override object GetPrimaryKey(Session row) => row.ConnectionId;
        }

        public readonly SessionHandle Session;
    }

    public sealed class SessionCols
    {
        public global::SpacetimeDB.Col<Session, SpacetimeDB.ConnectionId> ConnectionId { get; }
        public global::SpacetimeDB.Col<Session, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<Session, ulong> AccountId { get; }
        public global::SpacetimeDB.Col<Session, string> Username { get; }
        public global::SpacetimeDB.Col<Session, SpacetimeDB.Timestamp> LoginAt { get; }

        public SessionCols(string tableName)
        {
            ConnectionId = new global::SpacetimeDB.Col<Session, SpacetimeDB.ConnectionId>(tableName, "connection_id");
            Identity = new global::SpacetimeDB.Col<Session, SpacetimeDB.Identity>(tableName, "identity");
            AccountId = new global::SpacetimeDB.Col<Session, ulong>(tableName, "account_id");
            Username = new global::SpacetimeDB.Col<Session, string>(tableName, "username");
            LoginAt = new global::SpacetimeDB.Col<Session, SpacetimeDB.Timestamp>(tableName, "login_at");
        }
    }

    public sealed class SessionIxCols
    {
        public global::SpacetimeDB.IxCol<Session, SpacetimeDB.ConnectionId> ConnectionId { get; }
        public global::SpacetimeDB.IxCol<Session, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.IxCol<Session, ulong> AccountId { get; }

        public SessionIxCols(string tableName)
        {
            ConnectionId = new global::SpacetimeDB.IxCol<Session, SpacetimeDB.ConnectionId>(tableName, "connection_id");
            Identity = new global::SpacetimeDB.IxCol<Session, SpacetimeDB.Identity>(tableName, "identity");
            AccountId = new global::SpacetimeDB.IxCol<Session, ulong>(tableName, "account_id");
        }
    }
}
