// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class SessionClosedHandle : RemoteEventTableHandle<EventContext, SessionClosed>
        {
            public override string RemoteTableName => "session_closed";

            internal SessionClosedHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly SessionClosedHandle SessionClosed;
    }

    public sealed class SessionClosedCols
    {
        public global::SpacetimeDB.Col<SessionClosed, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<SessionClosed, SpacetimeDB.ConnectionId> ConnectionId { get; }
        public global::SpacetimeDB.Col<SessionClosed, SessionCloseReason> Reason { get; }

        public SessionClosedCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<SessionClosed, SpacetimeDB.Identity>(tableName, "identity");
            ConnectionId = new global::SpacetimeDB.Col<SessionClosed, SpacetimeDB.ConnectionId>(tableName, "connection_id");
            Reason = new global::SpacetimeDB.Col<SessionClosed, SessionCloseReason>(tableName, "reason");
        }
    }

    public sealed class SessionClosedIxCols
    {

        public SessionClosedIxCols(string tableName)
        {
        }
    }
}
