// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldTimeHandle : RemoteTableHandle<EventContext, WorldTime>
        {
            public override string RemoteTableName => "world_time";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(WorldTime row) => row.Id;

                public IdUniqueIndex(WorldTimeHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal WorldTimeHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(WorldTime row) => row.Id;
        }

        public readonly WorldTimeHandle WorldTime;
    }

    public sealed class WorldTimeCols
    {
        public global::SpacetimeDB.Col<WorldTime, uint> Id { get; }
        public global::SpacetimeDB.Col<WorldTime, uint> BandId { get; }
        public global::SpacetimeDB.Col<WorldTime, SpacetimeDB.Timestamp> ChangedAt { get; }

        public WorldTimeCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<WorldTime, uint>(tableName, "id");
            BandId = new global::SpacetimeDB.Col<WorldTime, uint>(tableName, "band_id");
            ChangedAt = new global::SpacetimeDB.Col<WorldTime, SpacetimeDB.Timestamp>(tableName, "changed_at");
        }
    }

    public sealed class WorldTimeIxCols
    {
        public global::SpacetimeDB.IxCol<WorldTime, uint> Id { get; }

        public WorldTimeIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<WorldTime, uint>(tableName, "id");
        }
    }
}
