// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class PopDungeonUI
{
    private UnityEngine.UI.Image closeButton;
    private TMPro.TextMeshProUGUI titleTex;
    private UnityEngine.RectTransform contents;

    private void InitAutoBind()
    {
        closeButton = Get<UnityEngine.UI.Image>("UIMask/Background/CloseButton");
        titleTex = Get<TMPro.TextMeshProUGUI>("UIMask/Background/Title/TitleTex");
        contents = Get<UnityEngine.RectTransform>("UIMask/Contents");

    }
}
