// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class MessageUI
{
    private UnityEngine.UI.Image icon;
    private TMPro.TextMeshProUGUI desc;
    private TMPro.TextMeshProUGUI name;

    private void InitAutoBind()
    {
        icon = Get<UnityEngine.UI.Image>("UserHeadSlot/icon");
        desc = Get<TMPro.TextMeshProUGUI>("Farme/Desc");
        name = Get<TMPro.TextMeshProUGUI>("Name");

    }
}
