// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class CharacterHeadSlot
{
    private TMPro.TextMeshProUGUI name;
    private UnityEngine.UI.Image icon;
    private UnityEngine.UI.Image selected;

    private void InitAutoBind()
    {
        name = Get<TMPro.TextMeshProUGUI>("Background/Name");
        icon = Get<UnityEngine.UI.Image>("icon");
        selected = Get<UnityEngine.UI.Image>("Selected");

    }
}
