// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class CharacterSlotUI
{
    private TMPro.TextMeshProUGUI characterName;
    private TMPro.TextMeshProUGUI characterLevel;
    private UnityEngine.RectTransform skeletonPoint;

    private void InitAutoBind()
    {
        characterName = Get<TMPro.TextMeshProUGUI>("CharacterName");
        characterLevel = Get<TMPro.TextMeshProUGUI>("CharacterLevel");
        skeletonPoint = Get<UnityEngine.RectTransform>("SkeletonPoint");

    }
}
