using System.Collections.Generic;
using Sirenix.OdinInspector;
using UnityEngine;
using UnityEngine.Audio;
#if UNITY_EDITOR
using System.IO;
using System.Linq;
using System.Text;
// 只 alias 需要的类型：整个 using UnityEditor 会让 FilePath 特性在
// Sirenix.OdinInspector.FilePathAttribute 和 UnityEditor.FilePathAttribute 之间产生歧义。
using AssetDatabase = UnityEditor.AssetDatabase;
#endif

namespace XFramework
{
    [CreateAssetMenu(fileName = "AudioConfiguration", menuName = "Configs/Audio/AudioConfiguration")]
    public class AudioConfiguration : OdinScriptableObject<AudioItemData>
    {
        [BoxGroup("混音器"), LabelText("混音器"), AssetList(Path = "AddressableAssets/")]
        public AudioMixer XMixer;

        [BoxGroup("混音器"), LabelText("混合组列表"), TableList(CellPadding = 3)]
        public List<AudioMixerGroupInfo> MixerGroupList;

        [BoxGroup("混音器"), LabelText("快照列表"), TableList(CellPadding = 3)]
        public List<AudioMixerSnapshotsInfo> MixerSnapshotsList;

        [BoxGroup("混音器"), LabelText("音乐预制体"),
         FilePath(ParentFolder = "Assets/AddressableAssets/Remote",Extensions =  "prefab")]
        public string MusicSourcePath;

        public AudioMixerGroup GetByMixerGroup(AudioMixerGroupType  type)
        {
            var temp = MixerGroupList.FindLast(temp =>
                temp.Type == type);
            if (temp != null)
                return temp.Group;
            return null;
        }

#if UNITY_EDITOR
        private const string AudioKeysOutputPath = "Assets/Scripts/Game/Scripts/AddressableKeys/AudioKeys.cs";
        private const string AudioKeysClassName = "AudioKeys";
        private const string AudioKeysNamespace = "XFramework";

        [BoxGroup("代码生成"), Button("生成 AudioKeys 常量类", ButtonSizes.Large), GUIColor(0.3f, 0.8f, 0.4f)]
        [PropertyTooltip("把 DataList 里的所有 audioID 生成为常量类，避免手写字符串。")]
        public void GenerateAudioKeys()
        {
            TryGenerateAudioKeys();
        }

        /// <summary>
        /// 生成 AudioKeys.cs。返回值给 ConfigTools 的一键流程用 —— 失败时要能中断后续步骤。
        /// </summary>
        public bool TryGenerateAudioKeys()
        {
            if (DataList == null || DataList.Count == 0)
            {
                Debug.LogWarning("[AudioKeys] 配置列表为空，没有可生成的音频 ID。");
                return false;
            }

            // 空 ID 无法生成常量，重复 ID 会让 GetDataByID 的结果取决于列表顺序，两者都要先暴露出来。
            var invalid = DataList
                .Where(item => item == null || string.IsNullOrWhiteSpace(item.audioID))
                .ToList();

            if (invalid.Count > 0)
            {
                Debug.LogError($"[AudioKeys] 有 {invalid.Count} 条配置的 audioID 为空，请先补全后再生成。");
                return false;
            }

            var duplicates = DataList
                .GroupBy(item => item.audioID)
                .Where(group => group.Count() > 1)
                .Select(group => group.Key)
                .ToList();

            if (duplicates.Count > 0)
            {
                Debug.LogError($"[AudioKeys] 存在重复的 audioID: {string.Join("、", duplicates)}，请先改成唯一值再生成。");
                return false;
            }

            string scriptContent = BuildAudioKeysScript();
            string directory = Path.GetDirectoryName(AudioKeysOutputPath);

            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(AudioKeysOutputPath, scriptContent, Encoding.UTF8);
            AssetDatabase.ImportAsset(AudioKeysOutputPath);

            Debug.Log($"[AudioKeys] 生成成功: {AudioKeysOutputPath}\n共 {DataList.Count} 条音频 ID 常量。");
            return true;
        }

        private string BuildAudioKeysScript()
        {
            StringBuilder sb = new StringBuilder();

            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     此文件由 AudioConfiguration.GenerateAudioKeys 自动生成。");
            sb.AppendLine("//     请不要手动修改，重新生成会覆盖内容。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine($"namespace {AudioKeysNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {AudioKeysClassName}");
            sb.AppendLine("    {");

            var usedNames = new HashSet<string>();

            // 保持 DataList 顺序，生成结果才能和配置表一一对应，diff 也更好读。
            foreach (var item in DataList)
            {
                string constName = MakeUniqueName(ToConstName(item.audioID), usedNames);

                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// {item.audioID} ({item.audioType})");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        public const string {constName} = \"{EscapeString(item.audioID)}\";");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// 把 audioID 转成合法的 C# 标识符，例如 Cursor_Click_01 -> CursorClick01。
        /// </summary>
        private static string ToConstName(string audioID)
        {
            StringBuilder sb = new StringBuilder();
            bool nextUpper = true;

            foreach (char c in audioID)
            {
                if (char.IsLetterOrDigit(c))
                {
                    // 标识符不能以数字开头。
                    if (sb.Length == 0 && char.IsDigit(c))
                    {
                        sb.Append('_');
                    }

                    sb.Append(nextUpper ? char.ToUpperInvariant(c) : c);
                    nextUpper = false;
                }
                else
                {
                    nextUpper = true;
                }
            }

            return sb.Length == 0 ? "Unnamed" : sb.ToString();
        }

        private static string MakeUniqueName(string baseName, HashSet<string> usedNames)
        {
            if (usedNames.Add(baseName))
            {
                return baseName;
            }

            int index = 2;

            while (!usedNames.Add(baseName + index))
            {
                index++;
            }

            return baseName + index;
        }

        private static string EscapeString(string value)
        {
            return value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"");
        }
#endif
    }

    [System.Serializable]
    public class AudioItemData : OdinDataItem<AudioItemData>
    {
        [BoxGroup("Audio"), LabelText("唯一音频ID"), HorizontalGroup("Audio/Row1")]
        public string audioID;

        [BoxGroup("Audio"), LabelText("音效类型"), HorizontalGroup("Audio/Row1")]
        public AudioType audioType;

        [BoxGroup("Audio/Clip"), HideLabel,
         AssetList(Path = "AddressableAssets"), PreviewField(60, alignment: ObjectFieldAlignment.Left)]
        [HorizontalGroup("Audio/Clip/Row2")]
        public AudioClip audioClip;

        [BoxGroup("Audio/Clip"), Range(0.1f, 1f), LabelText("初始音量大小"),
         HorizontalGroup("Audio/Clip/Row2"), VerticalGroup("Audio/Clip/Row2/Init")]
        public float InitVolume = 1;

        [BoxGroup("Audio/Clip"), Range(0.1f, 1f), LabelText("随机PitchMin"),
         HorizontalGroup("Audio/Clip/Row2"), VerticalGroup("Audio/Clip/Row2/Init")]
        public float soundPitchMin = 0.8f;

        [BoxGroup("Audio/Clip"), Range(0.1f, 1.2f), LabelText("随机PitchMax"),
         HorizontalGroup("Audio/Clip/Row2"), VerticalGroup("Audio/Clip/Row2/Init")]
        public float soundPitchMax = 1.2f;

        public override string GetID()
        {
            return audioID;
        }
    }


    [System.Serializable]
    public class AudioMixerGroupInfo
    {
        [BoxGroup("混音器"), LabelText("类型"), EnumPaging, HorizontalGroup("混音器/R")]
        public AudioMixerGroupType Type;

        [BoxGroup("混音器"), LabelText("混合器"), AssetList(Path = "AddressableAssets/")] [HorizontalGroup("混音器/R")]
        public AudioMixerGroup Group;
    }

    [System.Serializable]
    public class AudioMixerSnapshotsInfo
    {
        [BoxGroup("混音器"), LabelText("类型"), EnumPaging, HorizontalGroup("混音器/R")]
        public AudioSnapshotsType Type;

        [BoxGroup("混音器"), LabelText("混合器"), AssetList(Path = "AddressableAssets/")]
        public AudioMixerSnapshot Snapshot;
    }

    /// <summary>
    /// Audio混合器混合组类型
    /// </summary>
    public enum AudioMixerGroupType
    {
        /// <summary>
        /// 主混合器
        /// </summary>
        Master = 0,

        /// <summary>
        /// 环境音效主混合器
        /// </summary>
        AmbientMaster = 1,

        /// <summary>
        /// 环境音效混合器
        /// </summary>
        AmbientItem = 2,

        /// <summary>
        /// BGM主混合器
        /// </summary>
        BGMMaster = 3,

        /// <summary>
        /// BGM混合器
        /// </summary>
        BGMItem = 4,

        /// <summary>
        /// Music特效总混合器
        /// </summary>
        MusicMaster = 5,

        /// <summary>
        /// Music特效混合器
        /// </summary>
        MusicItem = 6,

        /// <summary>
        /// 人声总混合器
        /// </summary>
        HumanMaster = 7,

        /// <summary>
        /// 人声混合器
        /// </summary>
        HumanItem = 8,

        /// <summary>
        /// 视频音效混合器
        /// </summary>
        VideoMaster = 9,

        /// <summary>
        /// 视频混合器
        /// </summary>
        VideoItem = 10,
    }

    /// <summary>
    /// Audio 混合器快照类型
    /// </summary>
    public enum AudioSnapshotsType
    {
        /// <summary>
        /// 默认都有音效
        /// </summary>
        Normal = 0,

        /// <summary>
        /// 高人声,低其他音效
        /// </summary>
        Human = 1,

        /// <summary>
        /// Video 视频音效
        /// </summary>
        Video = 2,

        /// <summary>
        /// 全部停止
        /// </summary>
        Stop = 3,
    }
}

