// <auto-generated>
// 这个文件由 LubanManagerGeneratorWindow 自动生成，请勿手动修改。
// </auto-generated>

namespace XFramework
{
    public partial class LubanManager
    {
        private TbCharacterForm _tbCharacterForm;

        public TbCharacterForm TbCharacterForm
        {
            get
            {
                return LoadTable(
                    ref _tbCharacterForm,
                    AssetKeys.TbcharacterformPath,
                    json => new TbCharacterForm(json)
                );
            }
        }

        private TbCharacterJob _tbCharacterJob;

        public TbCharacterJob TbCharacterJob
        {
            get
            {
                return LoadTable(
                    ref _tbCharacterJob,
                    AssetKeys.TbcharacterjobPath,
                    json => new TbCharacterJob(json)
                );
            }
        }

        private TbDungeon _tbDungeon;

        public TbDungeon TbDungeon
        {
            get
            {
                return LoadTable(
                    ref _tbDungeon,
                    AssetKeys.TbdungeonPath,
                    json => new TbDungeon(json)
                );
            }
        }

        private TbDungeonArea _tbDungeonArea;

        public TbDungeonArea TbDungeonArea
        {
            get
            {
                return LoadTable(
                    ref _tbDungeonArea,
                    AssetKeys.TbdungeonareaPath,
                    json => new TbDungeonArea(json)
                );
            }
        }

        private TbLevelExp _tbLevelExp;

        public TbLevelExp TbLevelExp
        {
            get
            {
                return LoadTable(
                    ref _tbLevelExp,
                    AssetKeys.TblevelexpPath,
                    json => new TbLevelExp(json)
                );
            }
        }

        private TbTimeBand _tbTimeBand;

        public TbTimeBand TbTimeBand
        {
            get
            {
                return LoadTable(
                    ref _tbTimeBand,
                    AssetKeys.TbtimebandPath,
                    json => new TbTimeBand(json)
                );
            }
        }

        private TbTown _tbTown;

        public TbTown TbTown
        {
            get
            {
                return LoadTable(
                    ref _tbTown,
                    AssetKeys.TbtownPath,
                    json => new TbTown(json)
                );
            }
        }

        private TbTownNpc _tbTownNpc;

        public TbTownNpc TbTownNpc
        {
            get
            {
                return LoadTable(
                    ref _tbTownNpc,
                    AssetKeys.TbtownnpcPath,
                    json => new TbTownNpc(json)
                );
            }
        }

        private TbTownTrigger _tbTownTrigger;

        public TbTownTrigger TbTownTrigger
        {
            get
            {
                return LoadTable(
                    ref _tbTownTrigger,
                    AssetKeys.TbtowntriggerPath,
                    json => new TbTownTrigger(json)
                );
            }
        }

        partial void ClearGeneratedCache()
        {
            _tbCharacterForm = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbcharacterformPath);
            _tbCharacterJob = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbcharacterjobPath);
            _tbDungeon = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbdungeonPath);
            _tbDungeonArea = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbdungeonareaPath);
            _tbLevelExp = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TblevelexpPath);
            _tbTimeBand = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbtimebandPath);
            _tbTown = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbtownPath);
            _tbTownNpc = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbtownnpcPath);
            _tbTownTrigger = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbtowntriggerPath);
        }
    }
}
