// <auto-generated>
// 这个文件由 LubanManagerGeneratorWindow 自动生成，请勿手动修改。
// </auto-generated>

namespace XFramework
{
    public partial class LubanManager
    {
        private TbCharacterForm _tbCharacterForm;

        public TbCharacterForm TbCharacterForm
        {
            get
            {
                return LoadTable(
                    ref _tbCharacterForm,
                    AssetKeys.TbcharacterformPath,
                    json => new TbCharacterForm(json)
                );
            }
        }

        private TbCharacterJob _tbCharacterJob;

        public TbCharacterJob TbCharacterJob
        {
            get
            {
                return LoadTable(
                    ref _tbCharacterJob,
                    AssetKeys.TbcharacterjobPath,
                    json => new TbCharacterJob(json)
                );
            }
        }

        partial void ClearGeneratedCache()
        {
            _tbCharacterForm = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbcharacterformPath);
            _tbCharacterJob = null;
            AssetsManager.Instance.FreeAsset(AssetKeys.TbcharacterjobPath);
        }
    }
}
