// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class LoginUI
{
    private TMPro.TextMeshProUGUI title;
    private TMPro.TMP_InputField nameField;
    private TMPro.TMP_InputField passField;
    private UnityEngine.UI.Button loginButoon;
    private UnityEngine.UI.Button registerBtn;

    private void InitAutoBind()
    {
        title = Get<TMPro.TextMeshProUGUI>("UIMask/Background/Top/Title");
        nameField = Get<TMPro.TMP_InputField>("UIMask/Background/Farme/UserName/NameField");
        passField = Get<TMPro.TMP_InputField>("UIMask/Background/Farme/UserPass/PassField");
        loginButoon = Get<UnityEngine.UI.Button>("UIMask/Background/Farme/LoginButoon");
        registerBtn = Get<UnityEngine.UI.Button>("UIMask/Background/Farme/RegisterBtn");

    }
}
