// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class CreatCharacterUI
{
    private UnityEngine.RectTransform fall;
    private UnityEngine.RectTransform headContent;
    private UnityEngine.UI.Image artImage;
    private UnityEngine.RectTransform rightJobsPanel;

    private void InitAutoBind()
    {
        fall = Get<UnityEngine.RectTransform>("UIMask/Fall");
        headContent = Get<UnityEngine.RectTransform>("UIMask/HeadContent");
        artImage = Get<UnityEngine.UI.Image>("UIMask/ArtImage");
        rightJobsPanel = Get<UnityEngine.RectTransform>("UIMask/RightJobsPanel");

    }
}
