// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Account
    {
        [DataMember(Name = "account_id")]
        public ulong AccountId;
        [DataMember(Name = "username_key")]
        public string UsernameKey;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "password_hash")]
        public string PasswordHash;
        [DataMember(Name = "password_salt")]
        public string PasswordSalt;
        [DataMember(Name = "hash_iterations")]
        public uint HashIterations;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "last_login_at")]
        public SpacetimeDB.Timestamp? LastLoginAt;
        [DataMember(Name = "character_slots")]
        public uint CharacterSlots;

        public Account(
            ulong AccountId,
            string UsernameKey,
            string Username,
            string PasswordHash,
            string PasswordSalt,
            uint HashIterations,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp? LastLoginAt,
            uint CharacterSlots
        )
        {
            this.AccountId = AccountId;
            this.UsernameKey = UsernameKey;
            this.Username = Username;
            this.PasswordHash = PasswordHash;
            this.PasswordSalt = PasswordSalt;
            this.HashIterations = HashIterations;
            this.CreatedAt = CreatedAt;
            this.LastLoginAt = LastLoginAt;
            this.CharacterSlots = CharacterSlots;
        }

        public Account()
        {
            this.UsernameKey = "";
            this.Username = "";
            this.PasswordHash = "";
            this.PasswordSalt = "";
        }
    }
}
