// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AccountWallet
    {
        [DataMember(Name = "account_id")]
        public ulong AccountId;
        [DataMember(Name = "coin")]
        public ulong Coin;
        [DataMember(Name = "gem")]
        public ulong Gem;

        public AccountWallet(
            ulong AccountId,
            ulong Coin,
            ulong Gem
        )
        {
            this.AccountId = AccountId;
            this.Coin = Coin;
            this.Gem = Gem;
        }

        public AccountWallet()
        {
        }
    }
}
