// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CharacterSelection
    {
        [DataMember(Name = "connection_id")]
        public SpacetimeDB.ConnectionId ConnectionId;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "account_id")]
        public ulong AccountId;
        [DataMember(Name = "character_id")]
        public ulong CharacterId;
        [DataMember(Name = "character_name")]
        public string CharacterName;
        [DataMember(Name = "job_id")]
        public uint JobId;
        [DataMember(Name = "level")]
        public uint Level;
        [DataMember(Name = "entered_at")]
        public SpacetimeDB.Timestamp EnteredAt;
        [DataMember(Name = "form_id")]
        public uint FormId;
        [DataMember(Name = "town_id")]
        public uint TownId;

        public CharacterSelection(
            SpacetimeDB.ConnectionId ConnectionId,
            SpacetimeDB.Identity Identity,
            ulong AccountId,
            ulong CharacterId,
            string CharacterName,
            uint JobId,
            uint Level,
            SpacetimeDB.Timestamp EnteredAt,
            uint FormId,
            uint TownId
        )
        {
            this.ConnectionId = ConnectionId;
            this.Identity = Identity;
            this.AccountId = AccountId;
            this.CharacterId = CharacterId;
            this.CharacterName = CharacterName;
            this.JobId = JobId;
            this.Level = Level;
            this.EnteredAt = EnteredAt;
            this.FormId = FormId;
            this.TownId = TownId;
        }

        public CharacterSelection()
        {
            this.CharacterName = "";
        }
    }
}
