// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CharacterLocation
    {
        [DataMember(Name = "character_id")]
        public ulong CharacterId;
        [DataMember(Name = "account_id")]
        public ulong AccountId;
        [DataMember(Name = "town_id")]
        public uint TownId;
        [DataMember(Name = "entered_at")]
        public SpacetimeDB.Timestamp EnteredAt;

        public CharacterLocation(
            ulong CharacterId,
            ulong AccountId,
            uint TownId,
            SpacetimeDB.Timestamp EnteredAt
        )
        {
            this.CharacterId = CharacterId;
            this.AccountId = AccountId;
            this.TownId = TownId;
            this.EnteredAt = EnteredAt;
        }

        public CharacterLocation()
        {
        }
    }
}
