// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CharacterTransform
    {
        [DataMember(Name = "connection_id")]
        public SpacetimeDB.ConnectionId ConnectionId;
        [DataMember(Name = "town_id")]
        public uint TownId;
        [DataMember(Name = "character_id")]
        public ulong CharacterId;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "facing")]
        public int Facing;
        [DataMember(Name = "moving")]
        public bool Moving;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;

        public CharacterTransform(
            SpacetimeDB.ConnectionId ConnectionId,
            uint TownId,
            ulong CharacterId,
            SpacetimeDB.Identity Identity,
            float X,
            float Y,
            int Facing,
            bool Moving,
            SpacetimeDB.Timestamp UpdatedAt
        )
        {
            this.ConnectionId = ConnectionId;
            this.TownId = TownId;
            this.CharacterId = CharacterId;
            this.Identity = Identity;
            this.X = X;
            this.Y = Y;
            this.Facing = Facing;
            this.Moving = Moving;
            this.UpdatedAt = UpdatedAt;
        }

        public CharacterTransform()
        {
        }
    }
}
