// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Character
    {
        [DataMember(Name = "character_id")]
        public ulong CharacterId;
        [DataMember(Name = "account_id")]
        public ulong AccountId;
        [DataMember(Name = "name_key")]
        public string NameKey;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "job_id")]
        public uint JobId;
        [DataMember(Name = "level")]
        public uint Level;
        [DataMember(Name = "exp")]
        public ulong Exp;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "last_played_at")]
        public SpacetimeDB.Timestamp? LastPlayedAt;
        [DataMember(Name = "deleted_at")]
        public SpacetimeDB.Timestamp? DeletedAt;
        [DataMember(Name = "star")]
        public uint Star;
        [DataMember(Name = "stamina")]
        public uint Stamina;
        [DataMember(Name = "stamina_day")]
        public int StaminaDay;

        public Character(
            ulong CharacterId,
            ulong AccountId,
            string NameKey,
            string Name,
            uint JobId,
            uint Level,
            ulong Exp,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp? LastPlayedAt,
            SpacetimeDB.Timestamp? DeletedAt,
            uint Star,
            uint Stamina,
            int StaminaDay
        )
        {
            this.CharacterId = CharacterId;
            this.AccountId = AccountId;
            this.NameKey = NameKey;
            this.Name = Name;
            this.JobId = JobId;
            this.Level = Level;
            this.Exp = Exp;
            this.CreatedAt = CreatedAt;
            this.LastPlayedAt = LastPlayedAt;
            this.DeletedAt = DeletedAt;
            this.Star = Star;
            this.Stamina = Stamina;
            this.StaminaDay = StaminaDay;
        }

        public Character()
        {
            this.NameKey = "";
            this.Name = "";
        }
    }
}
