// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ChatMessage
    {
        [DataMember(Name = "message_id")]
        public ulong MessageId;
        [DataMember(Name = "channel")]
        public uint Channel;
        [DataMember(Name = "town_id")]
        public uint TownId;
        [DataMember(Name = "sender_character_id")]
        public ulong SenderCharacterId;
        [DataMember(Name = "sender_name")]
        public string SenderName;
        [DataMember(Name = "content")]
        public string Content;
        [DataMember(Name = "sent_at")]
        public SpacetimeDB.Timestamp SentAt;
        [DataMember(Name = "sender_job_id")]
        public uint SenderJobId;
        [DataMember(Name = "sender_form_id")]
        public uint SenderFormId;

        public ChatMessage(
            ulong MessageId,
            uint Channel,
            uint TownId,
            ulong SenderCharacterId,
            string SenderName,
            string Content,
            SpacetimeDB.Timestamp SentAt,
            uint SenderJobId,
            uint SenderFormId
        )
        {
            this.MessageId = MessageId;
            this.Channel = Channel;
            this.TownId = TownId;
            this.SenderCharacterId = SenderCharacterId;
            this.SenderName = SenderName;
            this.Content = Content;
            this.SentAt = SentAt;
            this.SenderJobId = SenderJobId;
            this.SenderFormId = SenderFormId;
        }

        public ChatMessage()
        {
            this.SenderName = "";
            this.Content = "";
        }
    }
}
