// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class IdentityBinding
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "account_id")]
        public ulong AccountId;
        [DataMember(Name = "bound_at")]
        public SpacetimeDB.Timestamp BoundAt;

        public IdentityBinding(
            SpacetimeDB.Identity Identity,
            ulong AccountId,
            SpacetimeDB.Timestamp BoundAt
        )
        {
            this.Identity = Identity;
            this.AccountId = AccountId;
            this.BoundAt = BoundAt;
        }

        public IdentityBinding()
        {
        }
    }
}
