// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MyAccountProfileRow
    {
        [DataMember(Name = "account_id")]
        public ulong AccountId;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "character_slots")]
        public uint CharacterSlots;

        public MyAccountProfileRow(
            ulong AccountId,
            string Username,
            uint CharacterSlots
        )
        {
            this.AccountId = AccountId;
            this.Username = Username;
            this.CharacterSlots = CharacterSlots;
        }

        public MyAccountProfileRow()
        {
            this.Username = "";
        }
    }
}
