// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MyCharacterRow
    {
        [DataMember(Name = "character_id")]
        public ulong CharacterId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "job_id")]
        public uint JobId;
        [DataMember(Name = "level")]
        public uint Level;
        [DataMember(Name = "exp")]
        public ulong Exp;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "last_played_at")]
        public SpacetimeDB.Timestamp? LastPlayedAt;

        public MyCharacterRow(
            ulong CharacterId,
            string Name,
            uint JobId,
            uint Level,
            ulong Exp,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp? LastPlayedAt
        )
        {
            this.CharacterId = CharacterId;
            this.Name = Name;
            this.JobId = JobId;
            this.Level = Level;
            this.Exp = Exp;
            this.CreatedAt = CreatedAt;
            this.LastPlayedAt = LastPlayedAt;
        }

        public MyCharacterRow()
        {
            this.Name = "";
        }
    }
}
