// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;

namespace ReDiv.Net.Bindings
{
    [SpacetimeDB.Type]
    public enum SessionCloseReason
    {
        KickedByNewLogin,
        LoggedOut,
        SwitchedAccount,
    }
}
