// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Session
    {
        [DataMember(Name = "connection_id")]
        public SpacetimeDB.ConnectionId ConnectionId;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "account_id")]
        public ulong AccountId;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "login_at")]
        public SpacetimeDB.Timestamp LoginAt;

        public Session(
            SpacetimeDB.ConnectionId ConnectionId,
            SpacetimeDB.Identity Identity,
            ulong AccountId,
            string Username,
            SpacetimeDB.Timestamp LoginAt
        )
        {
            this.ConnectionId = ConnectionId;
            this.Identity = Identity;
            this.AccountId = AccountId;
            this.Username = Username;
            this.LoginAt = LoginAt;
        }

        public Session()
        {
            this.Username = "";
        }
    }
}
