// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SessionClosed
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "connection_id")]
        public SpacetimeDB.ConnectionId ConnectionId;
        [DataMember(Name = "reason")]
        public SessionCloseReason Reason;

        public SessionClosed(
            SpacetimeDB.Identity Identity,
            SpacetimeDB.ConnectionId ConnectionId,
            SessionCloseReason Reason
        )
        {
            this.Identity = Identity;
            this.ConnectionId = ConnectionId;
            this.Reason = Reason;
        }

        public SessionClosed()
        {
        }
    }
}
