// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldTimeControl
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "override_band_id")]
        public uint OverrideBandId;

        public WorldTimeControl(
            uint Id,
            uint OverrideBandId
        )
        {
            this.Id = Id;
            this.OverrideBandId = OverrideBandId;
        }

        public WorldTimeControl()
        {
        }
    }
}
