// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldTime
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "band_id")]
        public uint BandId;
        [DataMember(Name = "changed_at")]
        public SpacetimeDB.Timestamp ChangedAt;

        public WorldTime(
            uint Id,
            uint BandId,
            SpacetimeDB.Timestamp ChangedAt
        )
        {
            this.Id = Id;
            this.BandId = BandId;
            this.ChangedAt = ChangedAt;
        }

        public WorldTime()
        {
        }
    }
}
