// ------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 AddressableKeyGeneratorOdinWindow 自动生成。
//     请不要手动修改，重新生成会覆盖内容。
// </auto-generated>
// ------------------------------------------------------------------------------

namespace XFramework
{
    public static class AssetKeys
    {
        public const string BD2MainTitle01Path = "Assets/AddressableAssets/Remote/Audio/BD2_Main_Title_01.wav";
        public const string BattleCursorClick01Path = "Assets/AddressableAssets/Remote/Audio/Common/Battle_Cursor_Click_01.wav";
        public const string BattleCursorMove01Path = "Assets/AddressableAssets/Remote/Audio/Common/Battle_Cursor_Move_01.wav";
        public const string CommonMenuSlideDown01Path = "Assets/AddressableAssets/Remote/Audio/Common/Common_Menu_SlideDown_01.wav";
        public const string CommonMenuSlideUp01Path = "Assets/AddressableAssets/Remote/Audio/Common/Common_Menu_SlideUp_01.wav";
        public const string CommonScreenMoves03Path = "Assets/AddressableAssets/Remote/Audio/Common/Common_Screen_Moves_03.wav";
        public const string CommonScreenMoves05Path = "Assets/AddressableAssets/Remote/Audio/Common/Common_Screen_Moves_05.wav";
        public const string CommonScreenMoves06Path = "Assets/AddressableAssets/Remote/Audio/Common/Common_Screen_Moves_06.wav";
        public const string UIButtonCancel02Path = "Assets/AddressableAssets/Remote/Audio/Common/UI_Button_Cancel_02.wav";
        public const string UIButtonClick02Path = "Assets/AddressableAssets/Remote/Audio/Common/UI_Button_Click_02.wav";
        public const string UIButtonDisable02Path = "Assets/AddressableAssets/Remote/Audio/Common/UI_Button_Disable_02.wav";
        public const string AudioConfigurationPath = "Assets/AddressableAssets/Remote/Configs/Audio/AudioConfiguration.asset";
        public const string XMixerPath = "Assets/AddressableAssets/Remote/Configs/Audio/XMixer.mixer";
        public const string UIPageConfigurationPath = "Assets/AddressableAssets/Remote/Configs/UI/UIPageConfiguration.asset";
        public const string MusicSourcePath = "Assets/AddressableAssets/Remote/Prefabs/AudioItem/MusicSource.prefab";
        public const string CommonUIPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/CommonUI.prefab";
        public const string IllustSpecial12AtlasPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Spine/illust_special12.atlas.txt";
        public const string IllustSpecial12Path = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Spine/illust_special12.json";
        public const string IllustSpecial12Path2 = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Spine/illust_special12.png";
        public const string IllustSpecial122Path = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Spine/illust_special12_2.png";
        public const string IllustSpecial12AtlasPath2 = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Spine/illust_special12_Atlas.asset";
        public const string IllustSpecial12SkeletonDataPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Spine/illust_special12_SkeletonData.asset";
        public const string IllustSpecial12IllustSpecial12Path = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Spine/illust_special12_illust_special12.mat";
        public const string IllustSpecial12IllustSpecial122Path = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Spine/illust_special12_illust_special12_2.mat";
        public const string BlueBGPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/BlueBG.png";
        public const string DiscordPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/Discord.png";
        public const string InterfaceGame21Path = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/InterfaceGame 2_1.png";
        public const string InterfaceGame23Path = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/InterfaceGame 2_3.png";
        public const string NumberButtonFill2xPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/NumberButton_Fill@2x.png";
        public const string NumberButtonOutline2xPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/NumberButton_Outline@2x.png";
        public const string SteamPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/Steam.png";
        public const string TwitterPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/Twitter.png";
        public const string BgmAlbumCommon011Path = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/bgm_album_common_01_1.png";
        public const string BtNormal8Path = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/bt_normal8.png";
        public const string BtNormal8DisPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/bt_normal8_dis.png";
        public const string IconSettingPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/icon_setting.png";
        public const string LoadingCirclePath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/loading_circle.png";
        public const string MaintitleLogo1Path = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/maintitle_logo1.png";
        public const string PopupiconExitPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/popupicon_exit.png";
        public const string Sactx0512x256UncompressedMainTitle883153411Path = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/sactx-0-512x256-Uncompressed-MainTitle-88315341 1.png";
        public const string Sepcialillust26IntroPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/sepcialillust_26 - Intro.png";
        public const string Sepcialillust26Path = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/sepcialillust_26.png";
        public const string TouchpointPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/CommonUI/Texture2D/touchpoint.png";
        public const string PopLoadingUIPath = "Assets/AddressableAssets/Remote/Prefabs/UGUI/PopLoadingUI/PopLoadingUI.prefab";
        public const string LoadingPath = "Assets/AddressableAssets/Remote/Video/Loading/Loading.asset";
    }
}
