// ------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 AddressableKeyGeneratorOdinWindow 自动生成。
//     请不要手动修改，重新生成会覆盖内容。
// </auto-generated>
// ------------------------------------------------------------------------------

namespace XFramework
{
    public static class AssetKeys
    {
        public const string AudioConfigurationPath = "Assets/AddressableAssets/Remote/Configs/Audio/AudioConfiguration.asset";
        public const string XMixerPath = "Assets/AddressableAssets/Remote/Configs/Audio/XMixer.mixer";
        public const string _01Path = "Assets/AddressableAssets/Remote/Configs/Drama/01.asset";
        public const string MusicSourcePath = "Assets/AddressableAssets/Remote/Prefabs/AudioItem/MusicSource.prefab";
        public const string DramaLogUIPath = "Assets/AddressableAssets/Remote/Prefabs/DramaLogUI/DramaLogUI.prefab";
        public const string LogItemUIPath = "Assets/AddressableAssets/Remote/Prefabs/DramaLogUI/LogItemUI.prefab";
        public const string 路径2xPath = "Assets/AddressableAssets/Remote/Prefabs/DramaLogUI/路径@2x.png";
        public const string ActorControllerPath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Actor/ActorController.prefab";
        public const string ActorSkeletonControllerPath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Actor/ActorSkeletonController.prefab";
        public const string ActorTextureControllerPath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Actor/ActorTextureController.prefab";
        public const string DramaBackgroundPath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/DramaBackground.prefab";
        public const string DramaRuntimeUIPath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/DramaRuntimeUI.prefab";
        public const string BG1Path = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Image/BG1.png";
        public const string TalkButton1Path = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Image/Talk_button_1.png";
        public const string TalkButton2Path = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Image/Talk_button_2.png";
        public const string TalkFrameBGPath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Image/Talk_frame_BG.png";
        public const string TalkFrameBG2Path = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Image/Talk_frame_BG2.png";
        public const string TalkNamePointPath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Image/Talk_name_point.png";
        public const string TalkNamePoint2Path = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Image/Talk_name_point2.png";
        public const string OptionControllerPath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Option/OptionController.prefab";
        public const string OptionCustomButtonPath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Option/OptionCustomButton.prefab";
        public const string FadePath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/ScreenEff/Fade.mat";
        public const string FadeControllerPath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/ScreenEff/FadeController.prefab";
        public const string ScreenActionControllerPath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/ScreenEff/ScreenActionController.prefab";
        public const string TalkActionControllerPath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Talk/TalkActionController.prefab";
        public const string TalkBackgroundControllerPath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Talk/TalkBackgroundController.prefab";
        public const string TalkContentControllerPath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Talk/TalkContentController.prefab";
        public const string TalkNameControllerPath = "Assets/AddressableAssets/Remote/Prefabs/DramaRuntimeUI/Talk/TalkNameController.prefab";
    }
}
