// ------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 AudioConfiguration.GenerateAudioKeys 自动生成。
//     请不要手动修改，重新生成会覆盖内容。
// </auto-generated>
// ------------------------------------------------------------------------------

namespace XFramework
{
    public static class AudioKeys
    {
        /// <summary>
        /// HomeBGM (BGM)
        /// </summary>
        public const string HomeBGM = "HomeBGM";
        /// <summary>
        /// FactorySuccessSound (Music)
        /// </summary>
        public const string FactorySuccessSound = "FactorySuccessSound";
        /// <summary>
        /// FactoryFailSound (Music)
        /// </summary>
        public const string FactoryFailSound = "FactoryFailSound";
        /// <summary>
        /// FactoryVictoryClipSound (Music)
        /// </summary>
        public const string FactoryVictoryClipSound = "FactoryVictoryClipSound";
        /// <summary>
        /// FactoryGameBgm (BGM)
        /// </summary>
        public const string FactoryGameBgm = "FactoryGameBgm";
        /// <summary>
        /// ShopHelpReturn (Music)
        /// </summary>
        public const string ShopHelpReturn = "ShopHelpReturn";
        /// <summary>
        /// ShopHelpPlace (Music)
        /// </summary>
        public const string ShopHelpPlace = "ShopHelpPlace";
        /// <summary>
        /// ShopHelpLose (Music)
        /// </summary>
        public const string ShopHelpLose = "ShopHelpLose";
        /// <summary>
        /// ShopHelpWin (Music)
        /// </summary>
        public const string ShopHelpWin = "ShopHelpWin";
        /// <summary>
        /// DranaStartBgm (BGM)
        /// </summary>
        public const string DranaStartBgm = "DranaStartBgm";
    }
}
