// ------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 UIKeysGenerator 自动生成。
//     请不要手动修改，重新生成会覆盖内容。
// </auto-generated>
// ------------------------------------------------------------------------------

namespace XFramework
{
    public static class UIKeys
    {
        /// <summary>
        /// 主界面UI (CommonUI)
        /// </summary>
        public const string CommonUI = "CommonUI";
        /// <summary>
        /// 大厅主UI (MainUI)
        /// </summary>
        public const string MainUI = "MainUI";
        /// <summary>
        /// 存档界面UI (LoadSaveGameUI)
        /// </summary>
        public const string LoadSaveGameUI = "LoadSaveGameUI";
        /// <summary>
        /// 设置用户名UI (SetUserNameUI)
        /// </summary>
        public const string SetUserNameUI = "SetUserNameUI";
        /// <summary>
        /// 游戏设置UI (GameSettingsUI)
        /// </summary>
        public const string GameSettingsUI = "GameSettingsUI";
        /// <summary>
        /// 回忆CG界面UI (PhotoAlbumUI)
        /// </summary>
        public const string PhotoAlbumUI = "PhotoAlbumUI";
        /// <summary>
        /// 通用Loading界面UI (PopLoadingUI)
        /// </summary>
        public const string PopLoadingUI = "PopLoadingUI";
        /// <summary>
        /// 地图信息UI (WordMapInfoUI)
        /// </summary>
        public const string WordMapInfoUI = "WordMapInfoUI";
        /// <summary>
        /// 角色点击UI (CharacterFunctionUI)
        /// </summary>
        public const string CharacterFunctionUI = "CharacterFunctionUI";
        /// <summary>
        /// 通用对话框UI (PopDialogueUI)
        /// </summary>
        public const string PopDialogueUI = "PopDialogueUI";
        /// <summary>
        /// 对话记录UI (DramaLogUI)
        /// </summary>
        public const string DramaLogUI = "DramaLogUI";
        /// <summary>
        /// 保存游戏UI (SaveGameUI)
        /// </summary>
        public const string SaveGameUI = "SaveGameUI";
        /// <summary>
        /// 开始约会UI (SetDatingTargetUI)
        /// </summary>
        public const string SetDatingTargetUI = "SetDatingTargetUI";
        /// <summary>
        /// 背包界面UI (InventoryUI)
        /// </summary>
        public const string InventoryUI = "InventoryUI";
        /// <summary>
        /// 爆点冲刺面板 (CrashSprintPanel)
        /// </summary>
        public const string CrashSprintPanel = "CrashSprintPanel";
        /// <summary>
        /// 游戏结算面板 (GameSettlePanel)
        /// </summary>
        public const string GameSettlePanel = "GameSettlePanel";
        /// <summary>
        /// 工厂材料选择面板 (FactoryMaterialSelectPanel)
        /// </summary>
        public const string FactoryMaterialSelectPanel = "FactoryMaterialSelectPanel";
        /// <summary>
        /// 工厂产品选择面板 (FactoryProductSelectPanel)
        /// </summary>
        public const string FactoryProductSelectPanel = "FactoryProductSelectPanel";
        /// <summary>
        /// 工厂主面板 (FactoryMainPanel)
        /// </summary>
        public const string FactoryMainPanel = "FactoryMainPanel";
        /// <summary>
        /// 赌场游戏进入面板 (CasinoGameEnterPanel)
        /// </summary>
        public const string CasinoGameEnterPanel = "CasinoGameEnterPanel";
        /// <summary>
        /// 厨房面板 (KitchenPanel)
        /// </summary>
        public const string KitchenPanel = "KitchenPanel";
        /// <summary>
        /// 女巫毒药面板 (WitchPoisonPanel)
        /// </summary>
        public const string WitchPoisonPanel = "WitchPoisonPanel";
        /// <summary>
        /// 拍照 (PhotoGamePanel)
        /// </summary>
        public const string PhotoGamePanel = "PhotoGamePanel";
        /// <summary>
        /// 布料商店 (ClothShopUI)
        /// </summary>
        public const string ClothShopUI = "ClothShopUI";
        /// <summary>
        /// 超市商店 (SuperMarketUI)
        /// </summary>
        public const string SuperMarketUI = "SuperMarketUI";
        /// <summary>
        /// 果蔬店商店 (FruitShopUI)
        /// </summary>
        public const string FruitShopUI = "FruitShopUI";
        /// <summary>
        /// 情趣用品店 (SexToyStoreUI)
        /// </summary>
        public const string SexToyStoreUI = "SexToyStoreUI";
        /// <summary>
        /// 钓鱼商店 (FishShopUI)
        /// </summary>
        public const string FishShopUI = "FishShopUI";
        /// <summary>
        /// 娃娃机启动UI (PopClawMachineTipUI)
        /// </summary>
        public const string PopClawMachineTipUI = "PopClawMachineTipUI";
        /// <summary>
        /// 娃娃机主UI (ClawMachineUI)
        /// </summary>
        public const string ClawMachineUI = "ClawMachineUI";
        /// <summary>
        /// 工厂模具结算面板 (FactoryMoldSettlePanel)
        /// </summary>
        public const string FactoryMoldSettlePanel = "FactoryMoldSettlePanel";
        /// <summary>
        /// 工厂模具管理面板 (FactoryMoldMgPanel)
        /// </summary>
        public const string FactoryMoldMgPanel = "FactoryMoldMgPanel";
        /// <summary>
        /// 工厂结算面板 (FactorySettlePanel)
        /// </summary>
        public const string FactorySettlePanel = "FactorySettlePanel";
        /// <summary>
        /// 抓娃娃机UI (ClawMachineGuideUI)
        /// </summary>
        public const string ClawMachineGuideUI = "ClawMachineGuideUI";
        /// <summary>
        /// 工厂处理面板 (FactoryProcessPanel)
        /// </summary>
        public const string FactoryProcessPanel = "FactoryProcessPanel";
        /// <summary>
        /// 解锁娃娃机展示界面 (PopUnlockDollWindowsUI)
        /// </summary>
        public const string PopUnlockDollWindowsUI = "PopUnlockDollWindowsUI";
        /// <summary>
        /// 工厂处理游戏面板 (FactoryProcessGamePanel)
        /// </summary>
        public const string FactoryProcessGamePanel = "FactoryProcessGamePanel";
        /// <summary>
        /// 通用获得道具界面 (PopRewardUI)
        /// </summary>
        public const string PopRewardUI = "PopRewardUI";
        /// <summary>
        /// 工厂处理介绍面板 (FactoryProcessIntroPanel)
        /// </summary>
        public const string FactoryProcessIntroPanel = "FactoryProcessIntroPanel";
        /// <summary>
        /// 线上玩法界面 (OnLineGameUI)
        /// </summary>
        public const string OnLineGameUI = "OnLineGameUI";
        /// <summary>
        /// 选择画稿图片 (PopSelectedPictureUI)
        /// </summary>
        public const string PopSelectedPictureUI = "PopSelectedPictureUI";
        /// <summary>
        /// 商店帮忙面板 (ShopHelpPanel)
        /// </summary>
        public const string ShopHelpPanel = "ShopHelpPanel";
        /// <summary>
        /// 商店帮忙进入面板 (ShopHelpEnterPanel)
        /// </summary>
        public const string ShopHelpEnterPanel = "ShopHelpEnterPanel";
        /// <summary>
        /// 炒菜结算面板 (CookSettlePanel)
        /// </summary>
        public const string CookSettlePanel = "CookSettlePanel";
        /// <summary>
        /// 属性获得界面 (PopRewardPropertyUI)
        /// </summary>
        public const string PopRewardPropertyUI = "PopRewardPropertyUI";
        /// <summary>
        /// 会展准备界面 (BoothGameStartUI)
        /// </summary>
        public const string BoothGameStartUI = "BoothGameStartUI";
        /// <summary>
        /// 服装选择界面 (PopClothingSelectedUI)
        /// </summary>
        public const string PopClothingSelectedUI = "PopClothingSelectedUI";
        /// <summary>
        /// 周边选择UI (PopMerchandiseSelectedUI)
        /// </summary>
        public const string PopMerchandiseSelectedUI = "PopMerchandiseSelectedUI";
        /// <summary>
        /// 钓鱼游戏进入面板 (FishGameEnterPanel)
        /// </summary>
        public const string FishGameEnterPanel = "FishGameEnterPanel";
        /// <summary>
        /// 钓鱼游戏面板 (FishGamePanel)
        /// </summary>
        public const string FishGamePanel = "FishGamePanel";
        /// <summary>
        /// 会展Game主UI (ExhibitionGameUI)
        /// </summary>
        public const string ExhibitionGameUI = "ExhibitionGameUI";
        /// <summary>
        /// 钓鱼游戏胜利面板 (FishGameWinPanel)
        /// </summary>
        public const string FishGameWinPanel = "FishGameWinPanel";
        /// <summary>
        /// 钓鱼游戏失败面板 (FishGameLosePanel)
        /// </summary>
        public const string FishGameLosePanel = "FishGameLosePanel";
        /// <summary>
        /// 会展结算面版 (PopExhibitionSettlementUI)
        /// </summary>
        public const string PopExhibitionSettlementUI = "PopExhibitionSettlementUI";
        /// <summary>
        /// 钓鱼老人离开后的提示面板 (FishGameUnavailablePanel)
        /// </summary>
        public const string FishGameUnavailablePanel = "FishGameUnavailablePanel";
        /// <summary>
        /// 钓鱼图鉴面板 (FishGalleryPanel)
        /// </summary>
        public const string FishGalleryPanel = "FishGalleryPanel";
        /// <summary>
        /// 服装制作主界面 (GarmentMakingCommonUI)
        /// </summary>
        public const string GarmentMakingCommonUI = "GarmentMakingCommonUI";
        /// <summary>
        /// 服装制作界面 (GarmentMakingUI)
        /// </summary>
        public const string GarmentMakingUI = "GarmentMakingUI";
        /// <summary>
        /// 打板游戏界面 (ClothingPatternMakingUI)
        /// </summary>
        public const string ClothingPatternMakingUI = "ClothingPatternMakingUI";
        /// <summary>
        /// 通用完成界面 (PopCompleteWindow)
        /// </summary>
        public const string PopCompleteWindow = "PopCompleteWindow";
        /// <summary>
        /// 通用失败界面 (PopFailWindows)
        /// </summary>
        public const string PopFailWindows = "PopFailWindows";
        /// <summary>
        /// 熨斗小游戏 (SewingMachineUI)
        /// </summary>
        public const string SewingMachineUI = "SewingMachineUI";
        /// <summary>
        /// 马吉房间游戏面板 (MachiRoomGamePanel)
        /// </summary>
        public const string MachiRoomGamePanel = "MachiRoomGamePanel";
        /// <summary>
        /// 拼图小游戏 (PuzzleUI)
        /// </summary>
        public const string PuzzleUI = "PuzzleUI";
        /// <summary>
        /// 滴胶固化玩法 (MedicinalSolutionUI)
        /// </summary>
        public const string MedicinalSolutionUI = "MedicinalSolutionUI";
        /// <summary>
        /// 服装制作喷漆小游戏 (DressMakingSprayPaintGamePanel)
        /// </summary>
        public const string DressMakingSprayPaintGamePanel = "DressMakingSprayPaintGamePanel";
        /// <summary>
        /// 宝石切割小游戏 (GemSmartSlicerUI)
        /// </summary>
        public const string GemSmartSlicerUI = "GemSmartSlicerUI";
        /// <summary>
        /// 如龙赛车小游戏 (RacingCarSewingMachinesUI)
        /// </summary>
        public const string RacingCarSewingMachinesUI = "RacingCarSewingMachinesUI";
        /// <summary>
        /// 服装制作刺绣填色小游戏 (DressMakingEmbroiderySimulationGamePanel)
        /// </summary>
        public const string DressMakingEmbroiderySimulationGamePanel = "DressMakingEmbroiderySimulationGamePanel";
        /// <summary>
        /// 服装上身小游戏 (UpperBodyUI)
        /// </summary>
        public const string UpperBodyUI = "UpperBodyUI";
        /// <summary>
        /// 礼物赠送面板 (GiftGivingPanel)
        /// </summary>
        public const string GiftGivingPanel = "GiftGivingPanel";
        /// <summary>
        /// 礼物赠送面板 (DramaRuntimeUI)
        /// </summary>
        public const string DramaRuntimeUI = "DramaRuntimeUI";
        /// <summary>
        /// 任务面板 (QuestPanel)
        /// </summary>
        public const string QuestPanel = "QuestPanel";
        /// <summary>
        /// 任务接受弹窗 (QuestAcceptPop)
        /// </summary>
        public const string QuestAcceptPop = "QuestAcceptPop";
        /// <summary>
        /// 任务奖励弹窗 (QuestRewardPop)
        /// </summary>
        public const string QuestRewardPop = "QuestRewardPop";
        /// <summary>
        /// 新手引导遮罩UI (TutorialUI)
        /// </summary>
        public const string TutorialUI = "TutorialUI";
    }
}
