// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class ReviseCharacterNameUI
{
    private TMPro.TMP_InputField nameField;
    private UnityEngine.UI.Button repeatButton;
    private UnityEngine.UI.Button cancelButton;
    private UnityEngine.UI.Button actionButton;

    private void InitAutoBind()
    {
        nameField = Get<TMPro.TMP_InputField>("UIMask/Background/Farme/NameField");
        repeatButton = Get<UnityEngine.UI.Button>("UIMask/Background/Farme/RepeatButton");
        cancelButton = Get<UnityEngine.UI.Button>("UIMask/Background/Farme/Buttons/CancelButton");
        actionButton = Get<UnityEngine.UI.Button>("UIMask/Background/Farme/Buttons/ActionButton");

    }
}
