// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class PopDialogueUI
{
    private TMPro.TextMeshProUGUI desc;
    private TMPro.TextMeshProUGUI title;
    private UnityEngine.UI.Button cancelButton;
    private UnityEngine.UI.Button actionButton;
    private TMPro.TextMeshProUGUI cancelTex;
    private TMPro.TextMeshProUGUI actionTex;

    private void InitAutoBind()
    {
        desc = Get<TMPro.TextMeshProUGUI>("UIMask/Background/Farme/Desc");
        title = Get<TMPro.TextMeshProUGUI>("UIMask/Background/Top/Title");
        cancelButton = Get<UnityEngine.UI.Button>("UIMask/Background/Farme/Buttons/CancelButton");
        actionButton = Get<UnityEngine.UI.Button>("UIMask/Background/Farme/Buttons/ActionButton");
        cancelTex = Get<TMPro.TextMeshProUGUI>("UIMask/Background/Farme/Buttons/CancelButton/cancelTex");
        actionTex = Get<TMPro.TextMeshProUGUI>("UIMask/Background/Farme/Buttons/ActionButton/actionTex");

    }
}
