
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class CharacterForm : Luban.BeanBase
{
    public CharacterForm(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        JobId = (int)_obj.GetValue("JobId");
        FormId = (int)_obj.GetValue("FormId");
        FormType = (int)_obj.GetValue("FormType");
        UnlockStar = (int)_obj.GetValue("UnlockStar");
        UnlockLevel = (int)_obj.GetValue("UnlockLevel");
        Name = (string)_obj.GetValue("Name");
        SortOrder = (int)_obj.GetValue("SortOrder");
        IconKey = (string)_obj.GetValue("IconKey");
        UnitPlateIconKey = (string)_obj.GetValue("UnitPlateIconKey");
        NameIconKey = (string)_obj.GetValue("NameIconKey");
        ArtImage = (string)_obj.GetValue("ArtImage");
        StillUnitPrefab = (string)_obj.GetValue("StillUnitPrefab");
        SkeletonUI = (string)_obj.GetValue("SkeletonUI");
        SkeletonScreen = (string)_obj.GetValue("SkeletonScreen");
    }

    public static CharacterForm DeserializeCharacterForm(JToken _buf)
    {
        return new CharacterForm(_buf);
    }

    /// <summary>
    /// 角色/职业ID
    /// </summary>
    public readonly int JobId;
    /// <summary>
    /// 形态ID
    /// </summary>
    public readonly int FormId;
    /// <summary>
    /// 形态线 基础=1 爆发=2
    /// </summary>
    public readonly int FormType;
    /// <summary>
    /// 门槛
    /// </summary>
    public readonly int UnlockStar;
    /// <summary>
    /// 觉醒所需等级(仅基础线用；爆发线靠宝石解锁，填0)
    /// </summary>
    public readonly int UnlockLevel;
    /// <summary>
    /// 形态名-中文原文
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 同一形态线内的排序(爆发形态左右翻的顺序)
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 头像-Addressable完整路径
    /// </summary>
    public readonly string IconKey;
    /// <summary>
    /// 略缩图路径
    /// </summary>
    public readonly string UnitPlateIconKey;
    /// <summary>
    /// 名字图片路径
    /// </summary>
    public readonly string NameIconKey;
    /// <summary>
    /// 立绘
    /// </summary>
    public readonly string ArtImage;
    /// <summary>
    /// 预览图预制体
    /// </summary>
    public readonly string StillUnitPrefab;
    /// <summary>
    /// UI展示预制体
    /// </summary>
    public readonly string SkeletonUI;
    /// <summary>
    /// 战斗Spine预制体
    /// </summary>
    public readonly string SkeletonScreen;


    public const int __ID__ = -991383699;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "JobId:" + JobId + ","
        + "FormId:" + FormId + ","
        + "FormType:" + FormType + ","
        + "UnlockStar:" + UnlockStar + ","
        + "UnlockLevel:" + UnlockLevel + ","
        + "Name:" + Name + ","
        + "SortOrder:" + SortOrder + ","
        + "IconKey:" + IconKey + ","
        + "UnitPlateIconKey:" + UnitPlateIconKey + ","
        + "NameIconKey:" + NameIconKey + ","
        + "ArtImage:" + ArtImage + ","
        + "StillUnitPrefab:" + StillUnitPrefab + ","
        + "SkeletonUI:" + SkeletonUI + ","
        + "SkeletonScreen:" + SkeletonScreen + ","
        + "}";
    }
}
}

