
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class CharacterJob : Luban.BeanBase
{
    public CharacterJob(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        JobId = (int)_obj.GetValue("JobId");
        Creatable = (bool)_obj.GetValue("Creatable");
        DefaultSpecId = (int)_obj.GetValue("DefaultSpecId");
        Name = (string)_obj.GetValue("Name");
        Subtitle = (string)_obj.GetValue("Subtitle");
        SortOrder = (int)_obj.GetValue("SortOrder");
    }

    public static CharacterJob DeserializeCharacterJob(JToken _buf)
    {
        return new CharacterJob(_buf);
    }

    public readonly int JobId;
    public readonly bool Creatable;
    public readonly int DefaultSpecId;
    public readonly string Name;
    public readonly string Subtitle;
    public readonly int SortOrder;


    public const int __ID__ = -1278902284;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "JobId:" + JobId + ","
        + "Creatable:" + Creatable + ","
        + "DefaultSpecId:" + DefaultSpecId + ","
        + "Name:" + Name + ","
        + "Subtitle:" + Subtitle + ","
        + "SortOrder:" + SortOrder + ","
        + "}";
    }
}
}

