
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class CharacterJob : Luban.BeanBase
{
    public CharacterJob(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        JobId = (int)_obj.GetValue("JobId");
        Creatable = (bool)_obj.GetValue("Creatable");
        Name = (string)_obj.GetValue("Name");
        SortOrder = (int)_obj.GetValue("SortOrder");
        MaxStar = (int)_obj.GetValue("MaxStar");
    }

    public static CharacterJob DeserializeCharacterJob(JToken _buf)
    {
        return new CharacterJob(_buf);
    }

    /// <summary>
    /// 角色ID
    /// </summary>
    public readonly int JobId;
    /// <summary>
    /// 能否在创建角色界面选择
    /// </summary>
    public readonly bool Creatable;
    /// <summary>
    /// 角色名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 星级上限。有二觉填6，没二觉填5
    /// </summary>
    public readonly int MaxStar;


    public const int __ID__ = -1278902284;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "JobId:" + JobId + ","
        + "Creatable:" + Creatable + ","
        + "Name:" + Name + ","
        + "SortOrder:" + SortOrder + ","
        + "MaxStar:" + MaxStar + ","
        + "}";
    }
}
}

