
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class CharacterForm : Luban.BeanBase
{
    public CharacterForm(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        JobId = (int)_obj.GetValue("JobId");
        FormId = (int)_obj.GetValue("FormId");
        FormType = (int)_obj.GetValue("FormType");
        UnlockStar = (int)_obj.GetValue("UnlockStar");
        UnlockLevel = (int)_obj.GetValue("UnlockLevel");
        Name = (string)_obj.GetValue("Name");
        SortOrder = (int)_obj.GetValue("SortOrder");
        IconKey = (string)_obj.GetValue("IconKey");
        ArtKey = (string)_obj.GetValue("ArtKey");
        SpineKey = (string)_obj.GetValue("SpineKey");
        VideoStartKey = (string)_obj.GetValue("VideoStartKey");
        VideoLoopKey = (string)_obj.GetValue("VideoLoopKey");
    }

    public static CharacterForm DeserializeCharacterForm(JToken _buf)
    {
        return new CharacterForm(_buf);
    }

    /// <summary>
    /// 角色/职业ID
    /// </summary>
    public readonly int JobId;
    /// <summary>
    /// 形态ID(同一角色内唯一，约定 基础线1~99 / 爆发线101起)
    /// </summary>
    public readonly int FormId;
    /// <summary>
    /// 形态线 基础=1 爆发=2
    /// </summary>
    public readonly int FormType;
    /// <summary>
    /// 星级门槛。基础线:达到该星级即切到这一形态(1基础/3一觉/6二觉)；爆发线:填6只表示它是6星形态
    /// </summary>
    public readonly int UnlockStar;
    /// <summary>
    /// 觉醒所需等级(仅基础线用；爆发线靠宝石解锁，填0)
    /// </summary>
    public readonly int UnlockLevel;
    /// <summary>
    /// 形态名-中文原文
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 同一形态线内的排序(爆发形态左右翻的顺序)
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 头像-Addressable完整路径
    /// </summary>
    public readonly string IconKey;
    /// <summary>
    /// 立绘-Addressable完整路径(只有基础形态填)
    /// </summary>
    public readonly string ArtKey;
    /// <summary>
    /// 战斗Spine-Addressable完整路径
    /// </summary>
    public readonly string SpineKey;
    /// <summary>
    /// 启动视频-AVPro MediaReference完整路径(播一次，可空)
    /// </summary>
    public readonly string VideoStartKey;
    /// <summary>
    /// 循环视频-AVPro MediaReference完整路径(觉醒/爆发形态要有)
    /// </summary>
    public readonly string VideoLoopKey;


    public const int __ID__ = -991383699;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "JobId:" + JobId + ","
        + "FormId:" + FormId + ","
        + "FormType:" + FormType + ","
        + "UnlockStar:" + UnlockStar + ","
        + "UnlockLevel:" + UnlockLevel + ","
        + "Name:" + Name + ","
        + "SortOrder:" + SortOrder + ","
        + "IconKey:" + IconKey + ","
        + "ArtKey:" + ArtKey + ","
        + "SpineKey:" + SpineKey + ","
        + "VideoStartKey:" + VideoStartKey + ","
        + "VideoLoopKey:" + VideoLoopKey + ","
        + "}";
    }
}
}

