
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class Dungeon : Luban.BeanBase
{
    public Dungeon(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        DungeonId = (int)_obj.GetValue("DungeonId");
        AreaId = (int)_obj.GetValue("AreaId");
        Name = (string)_obj.GetValue("Name");
        ThumbnailKey = (string)_obj.GetValue("ThumbnailKey");
        MaxStar = (int)_obj.GetValue("MaxStar");
        SortOrder = (int)_obj.GetValue("SortOrder");
    }

    public static Dungeon DeserializeDungeon(JToken _buf)
    {
        return new Dungeon(_buf);
    }

    /// <summary>
    /// 副本ID-全局唯一
    /// </summary>
    public readonly int DungeonId;
    /// <summary>
    /// 属于哪个副本区域-对应DungeonArea表的AreaId
    /// </summary>
    public readonly int AreaId;
    /// <summary>
    /// 副本名-中文原文-显示在格子上
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 略缩图-Addressable完整路径-格子上那张RawImage
    /// </summary>
    public readonly string ThumbnailKey;
    /// <summary>
    /// 最高可挑战星级1~6-实际能选到几星还要看通关进度
    /// </summary>
    public readonly int MaxStar;
    /// <summary>
    /// 同一区域内的排序
    /// </summary>
    public readonly int SortOrder;


    public const int __ID__ = -619892070;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "DungeonId:" + DungeonId + ","
        + "AreaId:" + AreaId + ","
        + "Name:" + Name + ","
        + "ThumbnailKey:" + ThumbnailKey + ","
        + "MaxStar:" + MaxStar + ","
        + "SortOrder:" + SortOrder + ","
        + "}";
    }
}
}

