
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class DungeonArea : Luban.BeanBase
{
    public DungeonArea(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        AreaId = (int)_obj.GetValue("AreaId");
        Name = (string)_obj.GetValue("Name");
        BackgroundKey = (string)_obj.GetValue("BackgroundKey");
        SortOrder = (int)_obj.GetValue("SortOrder");
    }

    public static DungeonArea DeserializeDungeonArea(JToken _buf)
    {
        return new DungeonArea(_buf);
    }

    /// <summary>
    /// 副本区域ID-全局唯一-城镇触发器Kind=2的TargetId指它
    /// </summary>
    public readonly int AreaId;
    /// <summary>
    /// 区域名-中文原文-显示在副本界面标题栏
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 区域背景预制体-Addressable完整路径-预制体上要有DungeonAreaBackground组件
    /// </summary>
    public readonly string BackgroundKey;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int SortOrder;


    public const int __ID__ = 1438489159;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "AreaId:" + AreaId + ","
        + "Name:" + Name + ","
        + "BackgroundKey:" + BackgroundKey + ","
        + "SortOrder:" + SortOrder + ","
        + "}";
    }
}
}

