
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class JobSpecialization : Luban.BeanBase
{
    public JobSpecialization(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        SpecId = (int)_obj.GetValue("SpecId");
        JobId = (int)_obj.GetValue("JobId");
        UnlockLevel = (int)_obj.GetValue("UnlockLevel");
        NameKey = (string)_obj.GetValue("NameKey");
        IconKey = (string)_obj.GetValue("IconKey");
        SortOrder = (int)_obj.GetValue("SortOrder");
    }

    public static JobSpecialization DeserializeJobSpecialization(JToken _buf)
    {
        return new JobSpecialization(_buf);
    }

    public readonly int SpecId;
    public readonly int JobId;
    public readonly int UnlockLevel;
    public readonly string NameKey;
    public readonly string IconKey;
    public readonly int SortOrder;


    public const int __ID__ = 1917962888;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "SpecId:" + SpecId + ","
        + "JobId:" + JobId + ","
        + "UnlockLevel:" + UnlockLevel + ","
        + "NameKey:" + NameKey + ","
        + "IconKey:" + IconKey + ","
        + "SortOrder:" + SortOrder + ","
        + "}";
    }
}
}

