
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class LevelExp : Luban.BeanBase
{
    public LevelExp(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Level = (int)_obj.GetValue("Level");
        ExpToNext = (int)_obj.GetValue("ExpToNext");
        MaxStamina = (int)_obj.GetValue("MaxStamina");
    }

    public static LevelExp DeserializeLevelExp(JToken _buf)
    {
        return new LevelExp(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 升到下一级所需经验。最高级填0(经验条按满显示)。占位数值Level*100待调
    /// </summary>
    public readonly int ExpToNext;
    /// <summary>
    /// 该等级的体力上限(每日重置回满)。占位数值待调
    /// </summary>
    public readonly int MaxStamina;


    public const int __ID__ = -2067006439;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Level:" + Level + ","
        + "ExpToNext:" + ExpToNext + ","
        + "MaxStamina:" + MaxStamina + ","
        + "}";
    }
}
}

