
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class SpecializationForm : Luban.BeanBase
{
    public SpecializationForm(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        SpecId = (int)_obj.GetValue("SpecId");
        Stage = (int)_obj.GetValue("Stage");
        UnlockLevel = (int)_obj.GetValue("UnlockLevel");
        Name = (string)_obj.GetValue("Name");
        ArtKey = (string)_obj.GetValue("ArtKey");
        IconKey = (string)_obj.GetValue("IconKey");
    }

    public static SpecializationForm DeserializeSpecializationForm(JToken _buf)
    {
        return new SpecializationForm(_buf);
    }

    public readonly int SpecId;
    public readonly int Stage;
    public readonly int UnlockLevel;
    public readonly string Name;
    public readonly string ArtKey;
    public readonly string IconKey;


    public const int __ID__ = 962490639;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "SpecId:" + SpecId + ","
        + "Stage:" + Stage + ","
        + "UnlockLevel:" + UnlockLevel + ","
        + "Name:" + Name + ","
        + "ArtKey:" + ArtKey + ","
        + "IconKey:" + IconKey + ","
        + "}";
    }
}
}

