
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace XFramework
{
public partial class Tables
{
    /// <summary>
    /// 角色/职业表。结构和分组都看 CharacterJob.xlsx 的表头（read_schema_from_file=True）
    /// </summary>
    public TbCharacterJob TbCharacterJob {get; }
    /// <summary>
    /// 角色形态表，联合主键 JobId+FormId。基础线(FormType=1)按星级现算当前形态，爆发线(FormType=2)一个角色可多个。结构看 CharacterForm.xlsx 表头
    /// </summary>
    public TbCharacterForm TbCharacterForm {get; }
    /// <summary>
    /// 城镇表。结构和分组看 Town.xlsx 表头。三列背景控制器对应早/中/晚三个时段
    /// </summary>
    public TbTown TbTown {get; }
    /// <summary>
    /// 时间段表。段数固定3段(早/中/晚)，只有边界(StartHour)可调
    /// </summary>
    public TbTimeBand TbTimeBand {get; }
    /// <summary>
    /// 等级表。升级所需经验 + 该等级的体力上限(每日重置)。经验条和体力条的分母都来自这里
    /// </summary>
    public TbLevelExp TbLevelExp {get; }
    /// <summary>
    /// 城镇NPC表。一行一个NPC，站在某个城镇的固定世界坐标上。纯客户端表现，服务端没有NPC概念。结构看 TownNpc.xlsx 表头（read_schema_from_file=True）
    /// </summary>
    public TbTownNpc TbTownNpc {get; }
    /// <summary>
    /// 城镇触发器表。一行一个矩形触发区，玩家走进去就生效：Kind=1 传送到别的城镇（走服务端 ChangeTown），Kind=2 打开副本界面。纯客户端表现，服务端不认识触发器（能不能去哪个城镇由服务端自己校验）。结构看 TownTrigger.xlsx 表头（read_schema_from_file=True）
    /// </summary>
    public TbTownTrigger TbTownTrigger {get; }
    /// <summary>
    /// 副本区域表(像DNF的格兰之森)。一个区域下面挂多个小副本，区域自己带一张背景。城镇触发器Kind=2的TargetId指的就是AreaId。纯客户端表现，服务端不认识副本。结构看 DungeonArea.xlsx 表头
    /// </summary>
    public TbDungeonArea TbDungeonArea {get; }
    /// <summary>
    /// 小副本表。一行一个副本(界面上一个格子)，MaxStar是配置允许的最高挑战星级，实际能选到几星还要看通关进度。纯客户端，等做进副本/结算时再把要校验的列开给服务端。结构看 Dungeon.xlsx 表头
    /// </summary>
    public TbDungeon TbDungeon {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        TbCharacterJob = new TbCharacterJob(loader("tbcharacterjob"));
        TbCharacterForm = new TbCharacterForm(loader("tbcharacterform"));
        TbTown = new TbTown(loader("tbtown"));
        TbTimeBand = new TbTimeBand(loader("tbtimeband"));
        TbLevelExp = new TbLevelExp(loader("tblevelexp"));
        TbTownNpc = new TbTownNpc(loader("tbtownnpc"));
        TbTownTrigger = new TbTownTrigger(loader("tbtowntrigger"));
        TbDungeonArea = new TbDungeonArea(loader("tbdungeonarea"));
        TbDungeon = new TbDungeon(loader("tbdungeon"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        TbCharacterJob.ResolveRef(this);
        TbCharacterForm.ResolveRef(this);
        TbTown.ResolveRef(this);
        TbTimeBand.ResolveRef(this);
        TbLevelExp.ResolveRef(this);
        TbTownNpc.ResolveRef(this);
        TbTownTrigger.ResolveRef(this);
        TbDungeonArea.ResolveRef(this);
        TbDungeon.ResolveRef(this);
    }
}

}

