
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace XFramework
{
public partial class Tables
{


      public Tables(System.Func<string, JArray> loader)
    {
        ResolveRef();
    }
    
     private void ResolveRef()
    {
    }
}

}

