
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 职业配置表（结构在 Defines/character.xml，字段带 group 区分客户端/服务端）
/// </summary>
public partial class TbCharacterJob
{
    private readonly System.Collections.Generic.Dictionary<int, CharacterJob> _dataMap;
    private readonly System.Collections.Generic.List<CharacterJob> _dataList;
    
    public TbCharacterJob(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CharacterJob>(_buf.Count);
        _dataList = new System.Collections.Generic.List<CharacterJob>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            CharacterJob _v;
            _v = global::XFramework.CharacterJob.DeserializeCharacterJob(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.JobId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, CharacterJob> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<CharacterJob> DataList => _dataList;

    public CharacterJob GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CharacterJob Get(int key) => _dataMap[key];
    public CharacterJob this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

