
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 副本区域表(像DNF的格兰之森)。一个区域下面挂多个小副本，区域自己带一张背景。城镇触发器Kind=2的TargetId指的就是AreaId。纯客户端表现，服务端不认识副本。结构看 DungeonArea.xlsx 表头
/// </summary>
public partial class TbDungeonArea
{
    private readonly System.Collections.Generic.Dictionary<int, DungeonArea> _dataMap;
    private readonly System.Collections.Generic.List<DungeonArea> _dataList;
    
    public TbDungeonArea(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DungeonArea>(_buf.Count);
        _dataList = new System.Collections.Generic.List<DungeonArea>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            DungeonArea _v;
            _v = global::XFramework.DungeonArea.DeserializeDungeonArea(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.AreaId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, DungeonArea> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<DungeonArea> DataList => _dataList;

    public DungeonArea GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DungeonArea Get(int key) => _dataMap[key];
    public DungeonArea this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

