
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 小副本表。一行一个副本(界面上一个格子)，MaxStar是配置允许的最高挑战星级，实际能选到几星还要看通关进度。纯客户端，等做进副本/结算时再把要校验的列开给服务端。结构看 Dungeon.xlsx 表头
/// </summary>
public partial class TbDungeon
{
    private readonly System.Collections.Generic.Dictionary<int, Dungeon> _dataMap;
    private readonly System.Collections.Generic.List<Dungeon> _dataList;
    
    public TbDungeon(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Dungeon>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Dungeon>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Dungeon _v;
            _v = global::XFramework.Dungeon.DeserializeDungeon(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.DungeonId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Dungeon> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Dungeon> DataList => _dataList;

    public Dungeon GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Dungeon Get(int key) => _dataMap[key];
    public Dungeon this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

