
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 专职表（结构在 Defines/character.xml）
/// </summary>
public partial class TbJobSpecialization
{
    private readonly System.Collections.Generic.Dictionary<int, JobSpecialization> _dataMap;
    private readonly System.Collections.Generic.List<JobSpecialization> _dataList;
    
    public TbJobSpecialization(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, JobSpecialization>(_buf.Count);
        _dataList = new System.Collections.Generic.List<JobSpecialization>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            JobSpecialization _v;
            _v = global::XFramework.JobSpecialization.DeserializeJobSpecialization(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.SpecId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, JobSpecialization> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<JobSpecialization> DataList => _dataList;

    public JobSpecialization GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public JobSpecialization Get(int key) => _dataMap[key];
    public JobSpecialization this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

