
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 等级表。升级所需经验 + 该等级的体力上限(每日重置)。经验条和体力条的分母都来自这里
/// </summary>
public partial class TbLevelExp
{
    private readonly System.Collections.Generic.Dictionary<int, LevelExp> _dataMap;
    private readonly System.Collections.Generic.List<LevelExp> _dataList;
    
    public TbLevelExp(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, LevelExp>(_buf.Count);
        _dataList = new System.Collections.Generic.List<LevelExp>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            LevelExp _v;
            _v = global::XFramework.LevelExp.DeserializeLevelExp(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, LevelExp> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<LevelExp> DataList => _dataList;

    public LevelExp GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public LevelExp Get(int key) => _dataMap[key];
    public LevelExp this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

