
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 专职形态表，联合主键 SpecId+Stage（结构在 Defines/character.xml）
/// </summary>
public partial class TbSpecializationForm
{
    private readonly System.Collections.Generic.List<SpecializationForm> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), SpecializationForm> _dataMapUnion;


    public TbSpecializationForm(JArray _buf)
    {
        _dataList = new System.Collections.Generic.List<SpecializationForm>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            SpecializationForm _v;
            _v = global::XFramework.SpecializationForm.DeserializeSpecializationForm(_ele);
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), SpecializationForm>(_buf.Count);
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.SpecId, _v.Stage), _v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<SpecializationForm> DataList => _dataList;


    public SpecializationForm Get(int SpecId, int Stage) => _dataMapUnion.TryGetValue((SpecId, Stage), out SpecializationForm __v) ? __v : default;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}
}

