
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 时间段表。段数固定3段(早/中/晚)，只有边界(StartHour)可调
/// </summary>
public partial class TbTimeBand
{
    private readonly System.Collections.Generic.Dictionary<int, TimeBand> _dataMap;
    private readonly System.Collections.Generic.List<TimeBand> _dataList;
    
    public TbTimeBand(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TimeBand>(_buf.Count);
        _dataList = new System.Collections.Generic.List<TimeBand>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            TimeBand _v;
            _v = global::XFramework.TimeBand.DeserializeTimeBand(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.BandId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, TimeBand> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<TimeBand> DataList => _dataList;

    public TimeBand GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TimeBand Get(int key) => _dataMap[key];
    public TimeBand this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

