
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 城镇表。结构和分组看 Town.xlsx 表头。三列背景控制器对应早/中/晚三个时段
/// </summary>
public partial class TbTown
{
    private readonly System.Collections.Generic.Dictionary<int, Town> _dataMap;
    private readonly System.Collections.Generic.List<Town> _dataList;
    
    public TbTown(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Town>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Town>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Town _v;
            _v = global::XFramework.Town.DeserializeTown(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.TownId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Town> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Town> DataList => _dataList;

    public Town GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Town Get(int key) => _dataMap[key];
    public Town this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

