
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 城镇NPC表。一行一个NPC，站在某个城镇的固定世界坐标上。纯客户端表现，服务端没有NPC概念。结构看 TownNpc.xlsx 表头（read_schema_from_file=True）
/// </summary>
public partial class TbTownNpc
{
    private readonly System.Collections.Generic.Dictionary<int, TownNpc> _dataMap;
    private readonly System.Collections.Generic.List<TownNpc> _dataList;
    
    public TbTownNpc(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TownNpc>(_buf.Count);
        _dataList = new System.Collections.Generic.List<TownNpc>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            TownNpc _v;
            _v = global::XFramework.TownNpc.DeserializeTownNpc(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.NpcId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, TownNpc> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<TownNpc> DataList => _dataList;

    public TownNpc GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TownNpc Get(int key) => _dataMap[key];
    public TownNpc this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

