
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace XFramework
{

/// <summary>
/// 城镇触发器表。一行一个矩形触发区，玩家走进去就生效：Kind=1 传送到别的城镇（走服务端 ChangeTown），Kind=2 打开副本界面。纯客户端表现，服务端不认识触发器（能不能去哪个城镇由服务端自己校验）。结构看 TownTrigger.xlsx 表头（read_schema_from_file=True）
/// </summary>
public partial class TbTownTrigger
{
    private readonly System.Collections.Generic.Dictionary<int, TownTrigger> _dataMap;
    private readonly System.Collections.Generic.List<TownTrigger> _dataList;
    
    public TbTownTrigger(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TownTrigger>(_buf.Count);
        _dataList = new System.Collections.Generic.List<TownTrigger>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            TownTrigger _v;
            _v = global::XFramework.TownTrigger.DeserializeTownTrigger(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.TriggerId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, TownTrigger> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<TownTrigger> DataList => _dataList;

    public TownTrigger GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TownTrigger Get(int key) => _dataMap[key];
    public TownTrigger this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

