
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TimeBand : Luban.BeanBase
{
    public TimeBand(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        BandId = (int)_obj.GetValue("BandId");
        Name = (string)_obj.GetValue("Name");
        StartHour = (int)_obj.GetValue("StartHour");
    }

    public static TimeBand DeserializeTimeBand(JToken _buf)
    {
        return new TimeBand(_buf);
    }

    /// <summary>
    /// 时段ID 早=1 中=2 晚=3。段数固定3段(城镇表是三列背景)
    /// </summary>
    public readonly int BandId;
    /// <summary>
    /// 时段名-中文原文
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 起始小时(服务器本地时0~23)。到下一段起始小时前都算这一段
    /// </summary>
    public readonly int StartHour;


    public const int __ID__ = -2013265214;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BandId:" + BandId + ","
        + "Name:" + Name + ","
        + "StartHour:" + StartHour + ","
        + "}";
    }
}
}

