
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class Town : Luban.BeanBase
{
    public Town(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        TownId = (int)_obj.GetValue("TownId");
        Name = (string)_obj.GetValue("Name");
        SortOrder = (int)_obj.GetValue("SortOrder");
        BgMorning = (string)_obj.GetValue("BgMorning");
        BgNoon = (string)_obj.GetValue("BgNoon");
        BgNight = (string)_obj.GetValue("BgNight");
    }

    public static Town DeserializeTown(JToken _buf)
    {
        return new Town(_buf);
    }

    /// <summary>
    /// 城镇ID
    /// </summary>
    public readonly int TownId;
    /// <summary>
    /// 城镇名-中文原文
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 排序
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 早时段背景控制器预制体-Addressable完整路径
    /// </summary>
    public readonly string BgMorning;
    /// <summary>
    /// 中时段背景控制器预制体-Addressable完整路径
    /// </summary>
    public readonly string BgNoon;
    /// <summary>
    /// 晚时段背景控制器预制体-Addressable完整路径
    /// </summary>
    public readonly string BgNight;


    public const int __ID__ = 2612914;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TownId:" + TownId + ","
        + "Name:" + Name + ","
        + "SortOrder:" + SortOrder + ","
        + "BgMorning:" + BgMorning + ","
        + "BgNoon:" + BgNoon + ","
        + "BgNight:" + BgNight + ","
        + "}";
    }
}
}

