
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TownTrigger : Luban.BeanBase
{
    public TownTrigger(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        TriggerId = (int)_obj.GetValue("TriggerId");
        TownId = (int)_obj.GetValue("TownId");
        Kind = (int)_obj.GetValue("Kind");
        TargetId = (int)_obj.GetValue("TargetId");
        PosX = (float)_obj.GetValue("PosX");
        PosY = (float)_obj.GetValue("PosY");
        Width = (float)_obj.GetValue("Width");
        Height = (float)_obj.GetValue("Height");
        Name = (string)_obj.GetValue("Name");
        IconPrefab = (string)_obj.GetValue("IconPrefab");
        ArriveOffsetX = (float)_obj.GetValue("ArriveOffsetX");
        ArriveOffsetY = (float)_obj.GetValue("ArriveOffsetY");
    }

    public static TownTrigger DeserializeTownTrigger(JToken _buf)
    {
        return new TownTrigger(_buf);
    }

    /// <summary>
    /// 触发器ID-全局唯一
    /// </summary>
    public readonly int TriggerId;
    /// <summary>
    /// 在哪个城镇-对应Town表的TownId
    /// </summary>
    public readonly int TownId;
    /// <summary>
    /// 类型:1=传送到其他城镇 2=打开副本界面
    /// </summary>
    public readonly int Kind;
    /// <summary>
    /// Kind=1时是对端传送点的TriggerId(目标城镇由它自己的TownId推出来)-Kind=2时是副本组ID(暂时填0)
    /// </summary>
    public readonly int TargetId;
    /// <summary>
    /// 矩形中心世界坐标X-以画面中心为0
    /// </summary>
    public readonly float PosX;
    /// <summary>
    /// 矩形中心世界坐标Y-地面大概在-3到-5之间
    /// </summary>
    public readonly float PosY;
    /// <summary>
    /// 矩形宽度-世界单位
    /// </summary>
    public readonly float Width;
    /// <summary>
    /// 矩形高度-世界单位
    /// </summary>
    public readonly float Height;
    /// <summary>
    /// 提示文字-中文原文-摆位窗口和以后的交互提示用
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 地面标记预制体-Addressable完整路径-可空
    /// </summary>
    public readonly string IconPrefab;
    /// <summary>
    /// 出口点相对本触发器中心的偏移X-从这个传送点出来时站的位置-用摆位窗口拖
    /// </summary>
    public readonly float ArriveOffsetX;
    /// <summary>
    /// 出口点相对本触发器中心的偏移Y-同上
    /// </summary>
    public readonly float ArriveOffsetY;


    public const int __ID__ = 2038399654;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TriggerId:" + TriggerId + ","
        + "TownId:" + TownId + ","
        + "Kind:" + Kind + ","
        + "TargetId:" + TargetId + ","
        + "PosX:" + PosX + ","
        + "PosY:" + PosY + ","
        + "Width:" + Width + ","
        + "Height:" + Height + ","
        + "Name:" + Name + ","
        + "IconPrefab:" + IconPrefab + ","
        + "ArriveOffsetX:" + ArriveOffsetX + ","
        + "ArriveOffsetY:" + ArriveOffsetY + ","
        + "}";
    }
}
}

