
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace XFramework
{

public sealed partial class TownNpc : Luban.BeanBase
{
    public TownNpc(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        NpcId = (int)_obj.GetValue("NpcId");
        TownId = (int)_obj.GetValue("TownId");
        Name = (string)_obj.GetValue("Name");
        PosX = (float)_obj.GetValue("PosX");
        PosY = (float)_obj.GetValue("PosY");
        Facing = (int)_obj.GetValue("Facing");
        SkeletonTown = (string)_obj.GetValue("SkeletonTown");
    }

    public static TownNpc DeserializeTownNpc(JToken _buf)
    {
        return new TownNpc(_buf);
    }

    /// <summary>
    /// NPC ID-全局唯一
    /// </summary>
    public readonly int NpcId;
    /// <summary>
    /// 站在哪个城镇-对应Town表的TownId
    /// </summary>
    public readonly int TownId;
    /// <summary>
    /// NPC名字-中文原文-显示在头顶
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 世界坐标X-以画面中心为0
    /// </summary>
    public readonly float PosX;
    /// <summary>
    /// 世界坐标Y-脚下的位置-地面大概在-3到-5之间
    /// </summary>
    public readonly float PosY;
    /// <summary>
    /// 朝向:1=朝右 -1=朝左
    /// </summary>
    public readonly int Facing;
    /// <summary>
    /// 城镇Spine预制体-Addressable完整路径-预制体上要有TownSkeletonController
    /// </summary>
    public readonly string SkeletonTown;


    public const int __ID__ = 531988175;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "NpcId:" + NpcId + ","
        + "TownId:" + TownId + ","
        + "Name:" + Name + ","
        + "PosX:" + PosX + ","
        + "PosY:" + PosY + ","
        + "Facing:" + Facing + ","
        + "SkeletonTown:" + SkeletonTown + ","
        + "}";
    }
}
}

