// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class CommonUI
{
    private TMPro.TextMeshProUGUI clickTex;

    private void InitAutoBind()
    {
        clickTex = Get<TMPro.TextMeshProUGUI>("UIMask/ClickTex");

    }
}
