// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class SelectCharacterUI
{
    private UnityEngine.UI.ScrollRect scrollView;
    private UnityEngine.UI.Button cancelButton;
    private UnityEngine.UI.Button enterButton;
    private UnityEngine.UI.Button quitButton;

    private void InitAutoBind()
    {
        scrollView = Get<UnityEngine.UI.ScrollRect>("UIMask/CharacterList/Scroll View");
        cancelButton = Get<UnityEngine.UI.Button>("UIMask/Buttons/CancelButton");
        enterButton = Get<UnityEngine.UI.Button>("UIMask/Buttons/EnterButton");
        quitButton = Get<UnityEngine.UI.Button>("UIMask/Buttons/QuitButton");

    }
}
