// ------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 AudioConfiguration.GenerateAudioKeys 自动生成。
//     请不要手动修改，重新生成会覆盖内容。
// </auto-generated>
// ------------------------------------------------------------------------------

namespace XFramework
{
    public static class AudioKeys
    {
        /// <summary>
        /// Cursor_Click_01 (Music)
        /// </summary>
        public const string CursorClick01 = "Cursor_Click_01";
        /// <summary>
        /// BD2_Main_Title_01 (BGM)
        /// </summary>
        public const string BD2MainTitle01 = "BD2_Main_Title_01";
    }
}
