// ------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 UIKeysGenerator 自动生成。
//     请不要手动修改，重新生成会覆盖内容。
// </auto-generated>
// ------------------------------------------------------------------------------

namespace XFramework
{
    public static class UIKeys
    {
        /// <summary>
        /// 对话框UI (PopDialogueUI)
        /// </summary>
        public const string PopDialogueUI = "PopDialogueUI";
        /// <summary>
        /// 登录界面UI (LoginUI)
        /// </summary>
        public const string LoginUI = "LoginUI";
        /// <summary>
        /// 外主界面 (CommonUI)
        /// </summary>
        public const string CommonUI = "CommonUI";
    }
}
