// ------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 UIKeysGenerator 自动生成。
//     请不要手动修改，重新生成会覆盖内容。
// </auto-generated>
// ------------------------------------------------------------------------------

namespace XFramework
{
    public static class UIKeys
    {
        /// <summary>
        /// 对话框UI (PopDialogueUI)
        /// </summary>
        public const string PopDialogueUI = "PopDialogueUI";
        /// <summary>
        /// 登录界面UI (LoginUI)
        /// </summary>
        public const string LoginUI = "LoginUI";
        /// <summary>
        /// 外主界面 (CommonUI)
        /// </summary>
        public const string CommonUI = "CommonUI";
        /// <summary>
        /// 选择角色界面 (SelectCharacterUI)
        /// </summary>
        public const string SelectCharacterUI = "SelectCharacterUI";
        /// <summary>
        /// 创建角色界面 (CreatCharacterUI)
        /// </summary>
        public const string CreatCharacterUI = "CreatCharacterUI";
        /// <summary>
        /// 角色名界面 (ReviseCharacterNameUI)
        /// </summary>
        public const string ReviseCharacterNameUI = "ReviseCharacterNameUI";
        /// <summary>
        /// 城镇主界面 (MainCommonUI)
        /// </summary>
        public const string MainCommonUI = "MainCommonUI";
        /// <summary>
        /// 聊天UI (PopMessageUI)
        /// </summary>
        public const string PopMessageUI = "PopMessageUI";
        /// <summary>
        /// 副本界面 (PopDungeonUI)
        /// </summary>
        public const string PopDungeonUI = "PopDungeonUI";
    }
}
