// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class PopMessageUI
{
    private UnityEngine.UI.Image wordChatButton;
    private UnityEngine.UI.Image bearbyButton;
    private UnityEngine.UI.ScrollRect scrollView;
    private TMPro.TMP_InputField inputFieldTMP;
    private UnityEngine.UI.Button sendButton;
    private UnityEngine.UI.Button closeButton;

    private void InitAutoBind()
    {
        wordChatButton = Get<UnityEngine.UI.Image>("UIMask/Background/Left/MemuButtons/WordChatButton");
        bearbyButton = Get<UnityEngine.UI.Image>("UIMask/Background/Left/MemuButtons/BearbyButton");
        scrollView = Get<UnityEngine.UI.ScrollRect>("UIMask/Background/Panel/Scroll View");
        inputFieldTMP = Get<TMPro.TMP_InputField>("UIMask/Background/Panel/InputField (TMP)");
        sendButton = Get<UnityEngine.UI.Button>("UIMask/Background/Panel/SendButton");
        closeButton = Get<UnityEngine.UI.Button>("UIMask/CloseButton");

    }
}
