// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class CharacterJobSlotUI
{
    private UnityEngine.UI.Image plateImg;
    private UnityEngine.UI.Button lastArrowButton;
    private UnityEngine.UI.Button nextArrowButton;
    private TMPro.TextMeshProUGUI name;
    private List<UnityEngine.UI.Image> starContent;

    private void InitAutoBind()
    {
        plateImg = Get<UnityEngine.UI.Image>("PlateImg");
        lastArrowButton = Get<UnityEngine.UI.Button>("NameFarme/LastArrowButton");
        nextArrowButton = Get<UnityEngine.UI.Button>("NameFarme/NextArrowButton");
        name = Get<TMPro.TextMeshProUGUI>("NameFarme/Name");
        starContent = Get<Transform>("StarContent").GetComponentsInChildren<UnityEngine.UI.Image>(true).Where(item => item.transform != Get<Transform>("StarContent")).ToList();

    }
}
