// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class CommonUI
{
    private UnityEngine.UI.Button quitButton;
    private UnityEngine.UI.Button settingsButton;
    private UnityEngine.UI.Button starGameClick;

    private void InitAutoBind()
    {
        quitButton = Get<UnityEngine.UI.Button>("UIMask/QuitButton");
        settingsButton = Get<UnityEngine.UI.Button>("UIMask/SettingsButton");
        starGameClick = Get<UnityEngine.UI.Button>("UIMask/StarGameClick");

    }
}
