// <auto-generated />
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public partial class DungeonSlot
{
    private UnityEngine.UI.RawImage rawImage;
    private TMPro.TextMeshProUGUI dungeonNameTex;
    private UnityEngine.UI.Button lastArrowButton;
    private UnityEngine.UI.Button nextArrowButton;
    private UnityEngine.RectTransform starContent;

    private void InitAutoBind()
    {
        rawImage = Get<UnityEngine.UI.RawImage>("Back/RawImage");
        dungeonNameTex = Get<TMPro.TextMeshProUGUI>("DungeonNameTex");
        lastArrowButton = Get<UnityEngine.UI.Button>("LevelFarme/LastArrowButton");
        nextArrowButton = Get<UnityEngine.UI.Button>("LevelFarme/NextArrowButton");
        starContent = Get<UnityEngine.RectTransform>("LevelFarme/StarContent");

    }
}
