// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ChangeTownHandler(ReducerEventContext ctx, uint townId);
        public event ChangeTownHandler? OnChangeTown;

        public void ChangeTown(uint townId)
        {
            conn.InternalCallReducer(new Reducer.ChangeTown(townId));
        }

        public bool InvokeChangeTown(ReducerEventContext ctx, Reducer.ChangeTown args)
        {
            if (OnChangeTown == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnChangeTown(
                ctx,
                args.TownId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ChangeTown : Reducer, IReducerArgs
        {
            [DataMember(Name = "town_id")]
            public uint TownId;

            public ChangeTown(uint TownId)
            {
                this.TownId = TownId;
            }

            public ChangeTown()
            {
            }

            string IReducerArgs.ReducerName => "change_town";
        }
    }
}
