// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CheckCharacterNameHandler(ReducerEventContext ctx, string name);
        public event CheckCharacterNameHandler? OnCheckCharacterName;

        public void CheckCharacterName(string name)
        {
            conn.InternalCallReducer(new Reducer.CheckCharacterName(name));
        }

        public bool InvokeCheckCharacterName(ReducerEventContext ctx, Reducer.CheckCharacterName args)
        {
            if (OnCheckCharacterName == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCheckCharacterName(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CheckCharacterName : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public CheckCharacterName(string Name)
            {
                this.Name = Name;
            }

            public CheckCharacterName()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "check_character_name";
        }
    }
}
