// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CheckVersionHandler(ReducerEventContext ctx, string clientVersion);
        public event CheckVersionHandler? OnCheckVersion;

        public void CheckVersion(string clientVersion)
        {
            conn.InternalCallReducer(new Reducer.CheckVersion(clientVersion));
        }

        public bool InvokeCheckVersion(ReducerEventContext ctx, Reducer.CheckVersion args)
        {
            if (OnCheckVersion == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCheckVersion(
                ctx,
                args.ClientVersion
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CheckVersion : Reducer, IReducerArgs
        {
            [DataMember(Name = "client_version")]
            public string ClientVersion;

            public CheckVersion(string ClientVersion)
            {
                this.ClientVersion = ClientVersion;
            }

            public CheckVersion()
            {
                this.ClientVersion = "";
            }

            string IReducerArgs.ReducerName => "check_version";
        }
    }
}
