// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateCharacterHandler(ReducerEventContext ctx, string name, uint jobId);
        public event CreateCharacterHandler? OnCreateCharacter;

        public void CreateCharacter(string name, uint jobId)
        {
            conn.InternalCallReducer(new Reducer.CreateCharacter(name, jobId));
        }

        public bool InvokeCreateCharacter(ReducerEventContext ctx, Reducer.CreateCharacter args)
        {
            if (OnCreateCharacter == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateCharacter(
                ctx,
                args.Name,
                args.JobId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateCharacter : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "job_id")]
            public uint JobId;

            public CreateCharacter(
                string Name,
                uint JobId
            )
            {
                this.Name = Name;
                this.JobId = JobId;
            }

            public CreateCharacter()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "create_character";
        }
    }
}
