// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteCharacterHandler(ReducerEventContext ctx, ulong characterId);
        public event DeleteCharacterHandler? OnDeleteCharacter;

        public void DeleteCharacter(ulong characterId)
        {
            conn.InternalCallReducer(new Reducer.DeleteCharacter(characterId));
        }

        public bool InvokeDeleteCharacter(ReducerEventContext ctx, Reducer.DeleteCharacter args)
        {
            if (OnDeleteCharacter == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteCharacter(
                ctx,
                args.CharacterId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteCharacter : Reducer, IReducerArgs
        {
            [DataMember(Name = "character_id")]
            public ulong CharacterId;

            public DeleteCharacter(ulong CharacterId)
            {
                this.CharacterId = CharacterId;
            }

            public DeleteCharacter()
            {
            }

            string IReducerArgs.ReducerName => "delete_character";
        }
    }
}
