// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LeaveCharacterHandler(ReducerEventContext ctx);
        public event LeaveCharacterHandler? OnLeaveCharacter;

        public void LeaveCharacter()
        {
            conn.InternalCallReducer(new Reducer.LeaveCharacter());
        }

        public bool InvokeLeaveCharacter(ReducerEventContext ctx, Reducer.LeaveCharacter args)
        {
            if (OnLeaveCharacter == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLeaveCharacter(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LeaveCharacter : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "leave_character";
        }
    }
}
