// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RefreshWorldTimeHandler(ReducerEventContext ctx);
        public event RefreshWorldTimeHandler? OnRefreshWorldTime;

        public void RefreshWorldTime()
        {
            conn.InternalCallReducer(new Reducer.RefreshWorldTime());
        }

        public bool InvokeRefreshWorldTime(ReducerEventContext ctx, Reducer.RefreshWorldTime args)
        {
            if (OnRefreshWorldTime == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRefreshWorldTime(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RefreshWorldTime : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "refresh_world_time";
        }
    }
}
