// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SelectCharacterHandler(ReducerEventContext ctx, ulong characterId);
        public event SelectCharacterHandler? OnSelectCharacter;

        public void SelectCharacter(ulong characterId)
        {
            conn.InternalCallReducer(new Reducer.SelectCharacter(characterId));
        }

        public bool InvokeSelectCharacter(ReducerEventContext ctx, Reducer.SelectCharacter args)
        {
            if (OnSelectCharacter == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSelectCharacter(
                ctx,
                args.CharacterId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SelectCharacter : Reducer, IReducerArgs
        {
            [DataMember(Name = "character_id")]
            public ulong CharacterId;

            public SelectCharacter(ulong CharacterId)
            {
                this.CharacterId = CharacterId;
            }

            public SelectCharacter()
            {
            }

            string IReducerArgs.ReducerName => "select_character";
        }
    }
}
