// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendNearbyMessageHandler(ReducerEventContext ctx, string content);
        public event SendNearbyMessageHandler? OnSendNearbyMessage;

        public void SendNearbyMessage(string content)
        {
            conn.InternalCallReducer(new Reducer.SendNearbyMessage(content));
        }

        public bool InvokeSendNearbyMessage(ReducerEventContext ctx, Reducer.SendNearbyMessage args)
        {
            if (OnSendNearbyMessage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSendNearbyMessage(
                ctx,
                args.Content
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendNearbyMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "content")]
            public string Content;

            public SendNearbyMessage(string Content)
            {
                this.Content = Content;
            }

            public SendNearbyMessage()
            {
                this.Content = "";
            }

            string IReducerArgs.ReducerName => "send_nearby_message";
        }
    }
}
