// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendWorldMessageHandler(ReducerEventContext ctx, string content);
        public event SendWorldMessageHandler? OnSendWorldMessage;

        public void SendWorldMessage(string content)
        {
            conn.InternalCallReducer(new Reducer.SendWorldMessage(content));
        }

        public bool InvokeSendWorldMessage(ReducerEventContext ctx, Reducer.SendWorldMessage args)
        {
            if (OnSendWorldMessage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSendWorldMessage(
                ctx,
                args.Content
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendWorldMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "content")]
            public string Content;

            public SendWorldMessage(string Content)
            {
                this.Content = Content;
            }

            public SendWorldMessage()
            {
                this.Content = "";
            }

            string IReducerArgs.ReducerName => "send_world_message";
        }
    }
}
