// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SwitchSpecializationHandler(ReducerEventContext ctx, ulong characterId, uint specId);
        public event SwitchSpecializationHandler? OnSwitchSpecialization;

        public void SwitchSpecialization(ulong characterId, uint specId)
        {
            conn.InternalCallReducer(new Reducer.SwitchSpecialization(characterId, specId));
        }

        public bool InvokeSwitchSpecialization(ReducerEventContext ctx, Reducer.SwitchSpecialization args)
        {
            if (OnSwitchSpecialization == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSwitchSpecialization(
                ctx,
                args.CharacterId,
                args.SpecId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SwitchSpecialization : Reducer, IReducerArgs
        {
            [DataMember(Name = "character_id")]
            public ulong CharacterId;
            [DataMember(Name = "spec_id")]
            public uint SpecId;

            public SwitchSpecialization(
                ulong CharacterId,
                uint SpecId
            )
            {
                this.CharacterId = CharacterId;
                this.SpecId = SpecId;
            }

            public SwitchSpecialization()
            {
            }

            string IReducerArgs.ReducerName => "switch_specialization";
        }
    }
}
