// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TownConfigSelfTestHandler(ReducerEventContext ctx);
        public event TownConfigSelfTestHandler? OnTownConfigSelfTest;

        public void TownConfigSelfTest()
        {
            conn.InternalCallReducer(new Reducer.TownConfigSelfTest());
        }

        public bool InvokeTownConfigSelfTest(ReducerEventContext ctx, Reducer.TownConfigSelfTest args)
        {
            if (OnTownConfigSelfTest == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTownConfigSelfTest(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TownConfigSelfTest : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "town_config_self_test";
        }
    }
}
