// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ReDiv.Net.Bindings
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateTransformHandler(ReducerEventContext ctx, float x, float y, int facing, bool moving);
        public event UpdateTransformHandler? OnUpdateTransform;

        public void UpdateTransform(float x, float y, int facing, bool moving)
        {
            conn.InternalCallReducer(new Reducer.UpdateTransform(x, y, facing, moving));
        }

        public bool InvokeUpdateTransform(ReducerEventContext ctx, Reducer.UpdateTransform args)
        {
            if (OnUpdateTransform == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateTransform(
                ctx,
                args.X,
                args.Y,
                args.Facing,
                args.Moving
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateTransform : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "facing")]
            public int Facing;
            [DataMember(Name = "moving")]
            public bool Moving;

            public UpdateTransform(
                float X,
                float Y,
                int Facing,
                bool Moving
            )
            {
                this.X = X;
                this.Y = Y;
                this.Facing = Facing;
                this.Moving = Moving;
            }

            public UpdateTransform()
            {
            }

            string IReducerArgs.ReducerName => "update_transform";
        }
    }
}
